# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.

"""BE-8003f golden-snapshot gate for the S1-S4 render sites.

Freezes the rendered output of the four v1 branch sites (S1 conductor/chain-drive, S2
multi_terminal per-terminal agent seed, S3 orchestrator mission prose, S4 worker mission
prose) with ``preset=None``, so an UNINTENDED render drift is caught byte-for-byte.

BE-9035c RE-BASELINE (owner-blessed): the execution-mode collapse (6 modes → 2) plus the
BE-9034 universal-subagent prose absorption DELIBERATELY changed the subagent renders, so
this fixture was regenerated to a NEW mode-by-harness key scheme: multi_terminal renders once;
subagent renders once PER DETECTED HARNESS (claude-code / codex / gemini / antigravity /
opencode / generic). The multi_terminal keys stay byte-identical to the pre-collapse render
(the collapse never touches the human-driven multi_terminal path) — if a multi_terminal
golden value EVER changes, multi_terminal broke: STOP and fix, do not re-baseline it. A
subagent-key change is only legitimate when it accompanies an INTENTIONAL prose change;
otherwise treat any drift as a regression to diagnose, not to bless away.

CONDUCTOR-CHAPTER CARVE-OUT (TSK-6232): the S1 conductor keys s1_chain_drive::* and s1_step_a
render the chain-conductor protocol chapter (CH_CHAIN_DRIVE / STEP A), edited by deliberate
conductor-protocol work and legitimately re-baselined on such a change — the multi_terminal-
never-changes rule above is the S2/S3/S4 HUMAN-path invariant (seed / exec-prompt / orchestrator-
and-worker prose), NOT these conductor-chapter keys. Re-baseline s1_chain_drive::* / s1_step_a
only alongside an intentional CH_CHAIN_DRIVE edit; any OTHER key drifting is still a regression.

BE-9260 RE-BASELINE: the S3/S4 orchestrator + worker prose hardcoded the Claude-Code-only
"TodoWrite" tool name for EVERY tool, including multi_terminal (a harness-neutral seat) —
that was itself the bug this project fixes. The rendered text now derives the task-list
phrasing from ``task_list_phrase(tool)`` (platform_registry.py): "TodoWrite list" only for
the detected claude-code harness, "task list" for every other tool INCLUDING multi_terminal.
The same closeout-signoff render also picked up a pre-existing, related bug fix: the
orchestrator body's "Project complete" line now derives the /giljo vs $giljo token from
``giljo_invocation(tool)`` instead of hardcoding "/giljo" — so the codex and antigravity
s3_orch keys flip from the wrong "/giljo" to the correct "$giljo" (matching how they're
actually installed, same as ``TestGiljoSignoffToken`` already pins for the worker signoff
block). The s4_worker keys additionally carry the mission-ordered shell-probe fallback:
Phase-1 Step 0 now tells workers what to do when ``python`` is not on PATH
(``echo $SHELL`` on POSIX / ``echo %COMSPEC%`` on Windows), so every s4_worker golden
gained that fallback line. This intentionally changed 21 golden keys (the multi_terminal
and per-harness s3_orch/s4_worker prose covered by the three changes above) — a
deliberate, mission-scoped exception to the "multi_terminal never changes" rule above,
not a silent re-baseline. Any OTHER key drifting is still a regression.

BE-9256 RE-BASELINE: the s4_worker git-integration-enabled block (Phase-4 "Git
Commit" instructions) taught a bare-SHA example -- `"commits": ["abc123"]` --
which is the exact shape the closeout validator now fails closed on. The
example is now a titled string (`"<sha> <one-line commit title>"`), so all 7
`s4_worker::*::git=True` keys (multi_terminal + the 6 per-harness subagent
renders) changed; every other key (git=False, s1-s3) is untouched — a
deliberate, narrowly-scoped re-baseline, not a silent one.

BE-9275b RE-BASELINE: the MCP tool prefix flipped `mcp__giljo_mcp__` ->
`mcp__giljo_hq__` (derived from `branding.MCP_ALIAS`), touching the
multi_terminal_prompt_builder.py per-terminal agent seed and the Claude-Code
ToolSearch bootstrap in the S2 execution prompt. Diff-verified: only the tool
prefix changed (`mcp__giljo_mcp__*` -> `mcp__giljo_hq__*` in the ToolSearch
select query and the bare seed lines) -- a deliberate, narrowly-scoped
re-baseline of `s2_seed_block::{claude-code,multi_terminal,codex,gemini}` and
`s2_exec_prompt::{claude-code,multi_terminal}`; every other key untouched.

The fixture is regenerated by running this module as a script:
    python tests/services/test_be8003f_render_ladder.py --write
"""

from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

import pytest

import giljo_mcp.prompts.launch_command_synth as lcs
from giljo_mcp.platform_registry import (
    EXECUTION_MODES,
    PLATFORM_PRESETS,
    PRESET_NAMES,
    get_preset,
)
from giljo_mcp.prompts.multi_terminal_prompt_builder import MultiTerminalPromptBuilder
from giljo_mcp.services.protocol_sections.agent_lifecycle import _generate_orchestrator_protocol
from giljo_mcp.services.protocol_sections.agent_protocol import _generate_agent_protocol
from giljo_mcp.services.protocol_sections.chapters_chain import (
    _build_ch_capability,
    _build_ch_chain_drive,
    _build_chain_drive_step_a,
)
from giljo_mcp.services.protocol_sections.orchestrator_body import render_capability_ladder


_FIXTURE = Path(__file__).with_name("_be8003f_render_goldens.json")

# Deterministic, side-effect-free render inputs. Fixed literals so the snapshot is a
# pure function of the builder templates, never of the environment.
_RUN_ID = "RUN-GOLD-0000"
_ORDER = ["P1-0000-0000", "P2-0000-0000", "P3-0000-0000"]
_JOB = "JOB-0000-0000"
_TENANT = "TENANT-GOLD"
_EXEC = "EXEC-0000-0000"
_COND = "COND-0000-0000"

# BE-9035c: the mode-by-harness golden matrix. After the collapse a subagent project's
# execution_mode is the single canonical ``subagent``; the DETECTED HARNESS (the render
# ``tool``) is what varies the per-harness prose. So S3/S4 render multi_terminal ONCE and
# subagent ONCE PER HARNESS — the 3 dedicated CLIs (claude-code/codex/gemini), the two
# universal-ladder harnesses (antigravity/opencode), and the ``generic`` floor. The old
# per-legacy-mode keys (s3_orch::claude_code_cli...) are gone by design (owner-blessed
# re-baseline — see the module docstring + DESIGN §6).
_SUBAGENT_HARNESSES: tuple[str, ...] = ("claude-code", "codex", "gemini", "antigravity", "opencode", "generic")


def _stub_jobs() -> list[SimpleNamespace]:
    """Three fake spawned agent jobs, one per cli_tool variant the seed routes on."""
    return [
        SimpleNamespace(agent_display_name="ui-impl", job_id="AJ-1", cli_tool="claude"),
        SimpleNamespace(agent_display_name="be-impl", job_id="AJ-2", cli_tool="codex"),
        SimpleNamespace(agent_display_name="doc", job_id="AJ-3", cli_tool=None),
    ]


def _stub_project() -> SimpleNamespace:
    return SimpleNamespace(
        id="PROJ-0000",
        name="Golden Project",
        project_type_id=None,
        series_number=None,
        taxonomy_alias="",
    )


def _render_goldens() -> dict[str, str]:
    """Render every S1-S4 entry point on the None/CLI (preset-less) path.

    Called by BOTH the fixture writer and the byte-identity test so the two can never
    drift. Uses NO ``preset`` argument -> exercises exactly the default (today's bytes).

    TSK-9263 ride-along: the goldens byte-pin ``pwsh -NoExit``; on a Windows
    contributor box without PS7 the launch-shell ladder would render ``powershell``
    and every Windows golden would mismatch. Pin pwsh-present for the render so the
    suite is host-independent (same pin as test_be6205_conductor_spawn_render).
    """
    with mock.patch.object(lcs, "_pwsh_available", return_value=True):
        return _render_goldens_unpinned()


def _render_goldens_unpinned() -> dict[str, str]:
    cases: dict[str, str] = {}
    builder = MultiTerminalPromptBuilder()

    # --- S1: conductor / chain-drive (chapters_chain.py) ---------------------
    for mode in (None, *EXECUTION_MODES):
        cases[f"s1_capability::{mode}"] = _build_ch_capability(mode, True)
    for mode in EXECUTION_MODES:
        cases[f"s1_chain_drive::{mode}"] = _build_ch_chain_drive(
            run_id=_RUN_ID,
            resolved_order=_ORDER,
            current_index=0,
            execution_mode=mode,
            conductor_agent_id=_COND,
            job_id=_JOB,
        )
    cases["s1_step_a"] = _build_chain_drive_step_a(_RUN_ID, "<<SPAWN_COMMAND_PLACEHOLDER>>")

    # --- S2: multi_terminal per-terminal agent seed --------------------------
    for tool in ("claude-code", "multi_terminal", "codex", "gemini"):
        cases[f"s2_seed_block::{tool}"] = builder._build_agent_seed_block(_stub_jobs(), tool)
        cases[f"s2_seed_block_empty::{tool}"] = builder._build_agent_seed_block([], tool)
    for tool in ("claude-code", "multi_terminal"):
        cases[f"s2_exec_prompt::{tool}"] = builder.build_execution_prompt(
            orchestrator_id="ORCH-0000",
            project=_stub_project(),
            agent_jobs=_stub_jobs(),
            git_enabled=True,
            tool=tool,
        )

    # --- S3: orchestrator mission prose — mode x harness (agent_lifecycle + orchestrator_body) -
    # multi_terminal renders once (its own tool); subagent renders once per detected harness.
    for cond in (False, True):
        cases[f"s3_orch::multi_terminal::conductor={cond}"] = _generate_orchestrator_protocol(
            _JOB, _TENANT, _EXEC, execution_mode="multi_terminal", tool="multi_terminal", is_chain_conductor=cond
        )
    for harness in _SUBAGENT_HARNESSES:
        for cond in (False, True):
            cases[f"s3_orch::subagent::{harness}::conductor={cond}"] = _generate_orchestrator_protocol(
                _JOB, _TENANT, _EXEC, execution_mode="subagent", tool=harness, is_chain_conductor=cond
            )

    # --- S4: worker mission prose — mode x harness (worker_body.py) ----------
    def _worker(execution_mode: str, tool: str, git: bool) -> str:
        return _generate_agent_protocol(
            _JOB,
            _TENANT,
            "implementer",
            agent_id=_EXEC,
            execution_mode=execution_mode,
            git_integration_enabled=git,
            job_type="implementer",
            tool=tool,
            # BE-9012d: render the PRIMARY (thread-bound) worker prose in the
            # golden — a real worker always has a resolved bound thread. The
            # None-degradation path is covered by test_be9012d_worker_hub_mission.
            comm_thread_id="comm-thread-golden",
        )

    for git in (False, True):
        cases[f"s4_worker::multi_terminal::git={git}"] = _worker("multi_terminal", "multi_terminal", git)
    for harness in _SUBAGENT_HARNESSES:
        for git in (False, True):
            cases[f"s4_worker::subagent::{harness}::git={git}"] = _worker("subagent", harness, git)

    return cases


def _load_fixture() -> dict[str, str]:
    if not _FIXTURE.exists():  # pragma: no cover - guard for a missing committed fixture
        raise AssertionError(
            f"Golden fixture missing: {_FIXTURE}. Regenerate with `python {Path(__file__).name} --write` and commit it."
        )
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


def test_s1_s4_render_byte_identical_on_none_path():
    """Every S1-S4 entry point renders BYTE-IDENTICAL to the committed golden on the
    preset-less (None/CLI) path. This is the D1 invariant: preset is None -> today's bytes."""
    golden = _load_fixture()
    current = _render_goldens()

    # Key set must match exactly — a dropped/added case is itself a regression signal.
    assert set(current) == set(golden), (
        f"case-set drift: added={sorted(set(current) - set(golden))} removed={sorted(set(golden) - set(current))}"
    )
    # Per-key compare for a readable diff on the first offending site.
    mismatches = [key for key in golden if current[key] != golden[key]]
    assert not mismatches, f"byte-identity BROKE on the None/CLI path for: {mismatches}"


@pytest.mark.parametrize("key", sorted(_render_goldens()))
def test_each_site_present_and_nonempty(key):
    """Sanity: every declared render case produces non-empty prose (an empty seed block
    for an empty team is the one legitimate empty case)."""
    value = _render_goldens()[key]
    if key.startswith("s2_seed_block_empty::"):
        assert value == ""
    else:
        assert value.strip(), f"empty render for {key}"


# =====================================================================================
# PART B — preset-render marker tests (D5.2) + helper/registry unit tests.
#
# On a preset-active render the ladder activates. These assert, per site x preset:
#   * NO gated CLI/terminal markers (where D3 gates them at that site)
#   * the [FLOOR] line is present
#   * the S1 inline-conducting marker is present for a non-terminal preset
# =====================================================================================

# All three registered presets are shell-less / non-terminal today.
_PRESETS = list(PRESET_NAMES)
# Terminal-launch markers S1 gates (the wt/gnome-terminal/osascript spawn command + the
# $DISPLAY/$WAYLAND_DISPLAY fail-loud clause — DoD-5 "$DISPLAY retirement").
_S1_GATED = ("wt -w 0", "gnome-terminal", "osascript", "$DISPLAY", "$WAYLAND_DISPLAY")
_FLOOR = "[FLOOR]"
_INLINE = "INLINE CONDUCTING"


def test_render_capability_ladder_shape():
    """The D4 formatter emits exactly the PREFERRED/FALLBACK/FLOOR shape."""
    out = render_capability_ladder("PREF", "FALL", "do X yourself", preset_display="Chat")
    assert out == (
        "[YOUR PATH — Chat]\n"
        "PREF\n"
        "[IF YOU CANNOT DO THE ABOVE]\n"
        "FALL\n"
        "[FLOOR] If none of the above works in your environment: post_to_thread on your "
        "coordination thread stating exactly what you cannot do, and show the user this "
        'line verbatim: "do X yourself".'
    )
    # Degenerate (no preset name) still has a header and the floor.
    assert render_capability_ladder("P", "F", "L").startswith("[YOUR PATH]\n")


def test_platform_has_shell_matches_workspace_model():
    """has_shell is True iff the platform is not a pure chat surface (workspace_model != none)."""
    by_name = {p.execution_mode: p for p in PLATFORM_PRESETS}
    assert by_name["web_sandbox"].has_shell is True
    assert by_name["desktop_app"].has_shell is True
    assert by_name["chat"].has_shell is False
    for p in PLATFORM_PRESETS:
        assert p.has_shell == (p.workspace_model != "none")


@pytest.mark.parametrize("preset_name", _PRESETS)
def test_s1_capability_preset_drops_terminal_markers(preset_name):
    preset = get_preset(preset_name)
    out = _build_ch_capability("multi_terminal", False, preset=preset)
    for marker in _S1_GATED:
        assert marker not in out, f"S1 capability[{preset_name}] leaked {marker!r}"
    assert _FLOOR in out
    assert _INLINE in out
    assert preset.display_label in out


@pytest.mark.parametrize("preset_name", _PRESETS)
def test_s1_step_a_and_chain_drive_preset_drop_terminal_markers(preset_name):
    preset = get_preset(preset_name)
    step_a = _build_chain_drive_step_a("RUN-X", "IGNORED-SPAWN", preset=preset)
    drive = _build_ch_chain_drive("RUN-X", ["P1", "P2"], 0, "multi_terminal", "COND", "JOB", preset=preset)
    for out, label in ((step_a, "step_a"), (drive, "chain_drive")):
        for marker in _S1_GATED:
            assert marker not in out, f"S1 {label}[{preset_name}] leaked {marker!r}"
        assert _INLINE in out, f"S1 {label}[{preset_name}] missing inline-conducting marker"
    assert _FLOOR in step_a


@pytest.mark.parametrize("preset_name", _PRESETS)
def test_s2_seed_block_preset_is_session_worded_with_floor(preset_name):
    preset = get_preset(preset_name)
    jobs = [SimpleNamespace(agent_display_name="ui", job_id="J1", cli_tool="claude")]
    out = MultiTerminalPromptBuilder()._build_agent_seed_block(jobs, "multi_terminal", preset=preset)
    assert _FLOOR in out
    assert "## PER-SESSION AGENT SEED" in out
    assert "NEW SESSION" in out
    # Never "terminal"/"CLI prompt" container wording on a preset-active render (D3-S2).
    assert "## PER-TERMINAL AGENT SEED" not in out
    assert "as the CLI\nprompt" not in out
    assert "### Terminal:" not in out
    # Chat (no execution environment) gets the code-vs-planning note.
    if not preset.has_shell:
        assert "code-WRITING job needs a session" in out


@pytest.mark.parametrize("preset_name", _PRESETS)
def test_s3_orchestrator_preset_has_waiting_ladder(preset_name):
    preset = get_preset(preset_name)
    out = _generate_orchestrator_protocol(
        "J", "T", "E", execution_mode="multi_terminal", tool="multi_terminal", preset=preset
    )
    assert _FLOOR in out
    assert "COORDINATING FROM A" in out  # the shell-less waiting ladder banner
    # None of the CLI-only asides D3-S3 gates (they do not live in the orchestrator prose,
    # so this must stay true — a regression that reintroduced one would fail here).
    for marker in ("ToolSearch", "TodoWrite", "sleep 1 "):
        assert marker not in out, f"S3 orchestrator[{preset_name}] leaked {marker!r}"


@pytest.mark.parametrize("preset_name", _PRESETS)
def test_s4_worker_shell_asides_gated_on_has_shell(preset_name):
    preset = get_preset(preset_name)
    out = _generate_agent_protocol(
        "J",
        "T",
        "impl",
        agent_id="E",
        execution_mode="multi_terminal",
        job_type="implementer",
        tool="multi_terminal",
        preset=preset,
    )
    if preset.has_shell:
        # web_sandbox / desktop_app keep the shell env-detection block unchanged: the
        # worker shell block uses `sleep N`, never the `sleep 1 N` background-wake trick.
        assert "ENVIRONMENT DETECTION" in out
        assert "sleep 1 " not in out
    else:
        # chat: shell asides suppressed, replaced by the no-shell ladder.
        assert "ENVIRONMENT DETECTION" not in out
        assert "Start-Sleep -Seconds N" not in out
        assert _FLOOR in out
        assert "NO SHELL (chat session)" in out


if __name__ == "__main__":  # pragma: no cover - fixture regeneration entry point
    import sys

    if "--write" in sys.argv:
        payload = json.dumps(_render_goldens(), indent=2, ensure_ascii=False)
        # Force LF so the fixture matches the repo line-ending convention (the golden
        # string VALUES are \n-escaped inside the JSON, so this only normalizes the
        # container, never the guarded prose).
        _FIXTURE.write_text(payload + "\n", encoding="utf-8", newline="\n")
        print(f"wrote {len(_render_goldens())} golden cases to {_FIXTURE}")
    else:
        print("pass --write to (re)generate the golden fixture")
