# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.


from enum import StrEnum


class ErrorCode(StrEnum):


    AUTH_INVALID_CREDENTIALS = "AUTH001"
    AUTH_TOKEN_EXPIRED = "AUTH002"
    AUTH_TOKEN_INVALID = "AUTH003"
    AUTH_UNAUTHORIZED = "AUTH004"
    AUTH_SESSION_EXPIRED = "AUTH005"
    AUTH_PIN_INVALID = "AUTH006"
    AUTH_PIN_EXPIRED = "AUTH007"
    AUTH_RATE_LIMIT_EXCEEDED = "AUTH008"
    AUTH_USER_NOT_FOUND = "AUTH009"
    AUTH_TENANT_MISMATCH = "AUTH010"
    AUTH_CSRF_VALIDATION_FAILED = "AUTH011"


    DB_CONNECTION_FAILED = "DB001"
    DB_QUERY_TIMEOUT = "DB002"
    DB_TRANSACTION_ROLLBACK = "DB003"
    DB_CONSTRAINT_VIOLATION = "DB004"
    DB_RECORD_NOT_FOUND = "DB005"
    DB_DUPLICATE_ENTRY = "DB006"
    DB_MIGRATION_FAILED = "DB007"
    DB_POOL_EXHAUSTED = "DB008"
    DB_DEADLOCK_DETECTED = "DB009"
    DB_INTEGRITY_ERROR = "DB010"


    WS_CONNECTION_FAILED = "WS001"
    WS_MESSAGE_SEND_FAILED = "WS002"
    WS_MESSAGE_PARSE_FAILED = "WS003"
    WS_AUTHENTICATION_FAILED = "WS004"
    WS_TENANT_ISOLATION_VIOLATED = "WS005"
    WS_BROADCAST_FAILED = "WS006"
    WS_DISCONNECTED_UNEXPECTEDLY = "WS007"
    WS_SUBSCRIPTION_FAILED = "WS008"
    WS_HEARTBEAT_TIMEOUT = "WS009"


    MCP_TOOL_EXECUTION_ERROR = "MCP001"
    MCP_AGENT_SPAWN_FAILED = "MCP002"
    MCP_CONTEXT_FETCH_FAILED = "MCP003"
    MCP_MISSION_NOT_FOUND = "MCP004"
    MCP_ORCHESTRATOR_ERROR = "MCP005"
    MCP_SUCCESSION_FAILED = "MCP006"
    MCP_AGENT_NOT_FOUND = "MCP007"
    MCP_INVALID_TENANT = "MCP008"
    MCP_TOOL_SCHEMA_INVALID = "MCP009"
    MCP_SESSION_EXPIRED = "MCP010"
    MCP_HTTP_TRANSPORT_ERROR = "MCP011"


    API_VALIDATION_ERROR = "API001"
    API_RATE_LIMIT_EXCEEDED = "API002"
    API_RESOURCE_NOT_FOUND = "API003"
    API_METHOD_NOT_ALLOWED = "API004"
    API_INTERNAL_ERROR = "API005"
    API_BAD_REQUEST = "API006"
    API_TIMEOUT = "API007"
    API_PAYLOAD_TOO_LARGE = "API008"
    API_UNSUPPORTED_MEDIA_TYPE = "API009"
    API_CONFLICT = "API010"
    API_DEPENDENCY_FAILED = "API011"

    def __str__(self) -> str:
        return self.value
