<template>
  <v-dialog v-model="isOpen" max-width="900" persistent scrollable>
    <v-card v-draggable class="smooth-border">
      <!-- Header -->
      <div class="dlg-header">
        <div
          class="agent-badge-sq"
          :style="{
            background: agentTintedBg,
            color: agentPrimaryColor,
          }"
        >{{ agentAbbr }}</div>
        <span class="dlg-title">Edit {{ agent?.agent_display_name || 'Agent' }} Mission</span>
        <v-btn icon variant="text" size="small" class="dlg-close" @click="handleClose">
          <v-icon icon="mdi-close" size="18" />
        </v-btn>
      </div>

      <div class="d-flex align-center ga-2 px-4 pb-2">
        <v-chip size="small" variant="outlined">
          Job: <code data-testid="mission-job-id">{{ agent?.job_id?.slice(0, 8) }}...</code>
        </v-chip>
        <v-chip size="x-small">
          {{ characterCount.toLocaleString() }} chars
        </v-chip>
      </div>

      <v-divider></v-divider>

      <!-- Mission Editor -->
      <v-card-text class="pa-4">
        <v-alert
          v-if="error"
          type="error"
          variant="tonal"
          density="compact"
          closable
          @click:close="error = null"
        >
          {{ error }}
        </v-alert>

        <v-textarea
          v-model="missionText"
          label="Agent Mission"
          placeholder="Enter the mission instructions for this agent..."
          variant="outlined"
          rows="15"
          auto-grow
          :counter="50000"
          :rules="missionRules"
          :loading="loading || missionPending"
          :disabled="loading || missionPending"
          class="mission-editor"
        >
          <template #prepend-inner>
            <v-icon>mdi-script-text</v-icon>
          </template>
        </v-textarea>

        <!-- Helper Text -->
        <v-alert type="info" variant="tonal" density="compact" class="mt-2">
          <div class="text-body-small">
            <strong>Important:</strong>
            <ul class="pl-4 mt-1">
              <li><strong>Mission is stored at JOB level</strong> (not per execution)</li>
              <li>Changes apply to ALL executions on job {{ agent?.job_id?.slice(0, 8) }}...</li>
              <li>If succession has occurred, all instances share this mission</li>
              <li>Original mission was generated by orchestrator</li>
              <li>You can refine or adjust as needed</li>
            </ul>
          </div>
        </v-alert>

        <!-- Execution Count (if succession has occurred) -->
        <v-alert
          v-if="executionCount > 1"
          type="warning"
          variant="tonal"
          density="compact"
          class="mt-2"
        >
          <div class="text-body-small">
            <v-icon size="small" start>mdi-alert</v-icon>
            This job has <strong>{{ executionCount }} executions</strong> (succession has occurred).
            Mission changes will affect all instances.
          </div>
        </v-alert>
      </v-card-text>

      <v-divider></v-divider>

      <!-- Actions -->
      <div class="dlg-footer">
        <v-btn
          variant="text"
          :disabled="!hasChanges || loading"
          @click="resetToOriginal"
        >
          <v-icon start>mdi-restore</v-icon>
          Reset
        </v-btn>
        <v-spacer />
        <v-btn
          variant="text"
          :disabled="loading"
          @click="handleClose"
        >
          Cancel
        </v-btn>
        <v-btn
          color="primary"
          variant="flat"
          :loading="loading"
          :disabled="!isValid || !hasChanges"
          @click="saveMission"
        >
          <v-icon start>mdi-content-save</v-icon>
          Save Mission
        </v-btn>
      </div>
    </v-card>
  </v-dialog>

  <!-- Unsaved Changes Confirmation -->
  <v-dialog v-model="showDiscardDialog" max-width="400" persistent z-index="2600">
    <v-card class="smooth-border">
      <div class="dlg-header dlg-header--warning">
        <v-icon class="dlg-icon">mdi-alert</v-icon>
        <span class="dlg-title">Unsaved Changes</span>
        <v-btn icon variant="text" size="small" class="dlg-close" @click="showDiscardDialog = false">
          <v-icon icon="mdi-close" size="18" />
        </v-btn>
      </div>
      <v-divider />
      <v-card-text class="pa-4">
        You have unsaved changes. Are you sure you want to close?
      </v-card-text>
      <v-divider />
      <div class="dlg-footer">
        <v-spacer />
        <v-btn variant="text" @click="showDiscardDialog = false">Keep Editing</v-btn>
        <v-btn color="warning" variant="flat" @click="discardAndClose">Discard</v-btn>
      </div>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { ref, computed, watch, getCurrentInstance } from 'vue'
import api from '@/services/api'
import { getAgentColor as getAgentColorConfig } from '@/config/agentColors'
import { hexToRgba } from '@/utils/colorUtils'

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  agent: {
    type: Object,
    default: null,
  },
})

const emit = defineEmits(['update:modelValue', 'mission-updated'])

// Get API instance (use injected $api if available, otherwise use imported api)
const instance = getCurrentInstance()
const apiClient = instance?.appContext.config.globalProperties.$api || api

// State
const missionText = ref('')
const originalMission = ref('')
const loading = ref(false)
// BE-9416: true while a truncated mission is being topped up by the store.
const missionPending = ref(false)
const error = ref(null)
const showDiscardDialog = ref(false)

// Computed
const isOpen = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val),
})

const characterCount = computed(() => {
  return missionText.value?.length || 0
})

const hasChanges = computed(() => {
  return missionText.value !== originalMission.value
})

const isValid = computed(() => {
  const trimmed = missionText.value?.trim() || ''
  return trimmed.length > 0 && trimmed.length <= 50000
})

const executionCount = computed(() => {
  return props.agent?.execution_count || 1
})

const agentPrimaryColor = computed(() => {
  return getAgentColorConfig(props.agent?.agent_display_name).hex
})

const agentTintedBg = computed(() => {
  return hexToRgba(agentPrimaryColor.value, 0.15)
})

const agentAbbr = computed(() => {
  const name = props.agent?.agent_display_name
  if (!name) return '?'
  return name
    .split(/[\s_-]+/)
    .map(word => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
})

// Validation rules
const missionRules = [
  (v) => !!v?.trim() || 'Mission is required',
  (v) => (v?.length || 0) <= 50000 || 'Mission must be less than 50,000 characters',
]

// BE-9416: a mission arriving over the WebSocket may be an EXCERPT.
//
// agent:created / agent:mission_updated bound the mission they carry so it clears
// the cross-worker broker's byte cap, and flag it with mission_truncated; the store
// then fetches the full text and patches the row. Two guards, because this editor
// SAVES what it is seeded with -- an excerpt seeded here and saved would overwrite
// the real mission with a fragment of itself.
//
// 1. Never seed from a mission known to be truncated. Waiting for the top-up is the
//    only thing that actually closes the save-back loss: a guard that merely
//    re-seeds correctly still leaves a fast operator able to save the excerpt in
//    the few hundred ms before the full text lands.
// 2. Never re-seed once the operator has edited. The top-up patches the store row,
//    which re-fires this watch; without this it would silently discard whatever
//    they had typed. (An external agent:mission_updated could already do this on
//    master; the top-up makes it routine rather than rare, so it is handled here.)
watch(
  () => props.agent,
  (newAgent) => {
    if (hasChanges.value) return

    if (newAgent?.mission_truncated) {
      // The full text is on its way; show the field as loading rather than
      // presenting a fragment (or a bare empty box) as if it were the mission.
      missionPending.value = true
      missionText.value = ''
      originalMission.value = ''
      error.value = null
      return
    }
    missionPending.value = false

    if (newAgent?.mission) {
      missionText.value = newAgent.mission
      originalMission.value = newAgent.mission
    } else {
      missionText.value = ''
      originalMission.value = ''
    }
    error.value = null
  },
  { immediate: true }
)

// Methods
async function saveMission() {
  if (!isValid.value || !hasChanges.value) return

  loading.value = true
  error.value = null

  try {
    const response = await apiClient.agentJobs.updateMission(props.agent.id, {
      mission: missionText.value,
    })

    if (response.data.success) {
      // Update original mission to reflect saved state
      originalMission.value = missionText.value

      // Emit event for parent to update
      emit('mission-updated', {
        jobId: props.agent.id,
        mission: missionText.value,
      })

      // Close modal
      isOpen.value = false
    }
  } catch (err) {
    console.error('[AgentMissionEditModal] Failed to save mission:', err)
    error.value = err.response?.data?.detail || 'Failed to save mission'
  } finally {
    loading.value = false
  }
}

function resetToOriginal() {
  missionText.value = originalMission.value
  error.value = null
}

function handleClose() {
  if (hasChanges.value) {
    showDiscardDialog.value = true
    return
  }
  isOpen.value = false
}

function discardAndClose() {
  showDiscardDialog.value = false
  resetToOriginal()
  isOpen.value = false
}
</script>

<style scoped>
.mission-editor :deep(.v-field__input) {
  font-family: 'IBM Plex Mono', monospace;
  font-size: 0.875rem;
}

.mission-editor :deep(.v-counter) {
  font-size: 0.75rem;
}
</style>
