# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.

"""
Project and session-related models for Giljo HQ.

This module contains models for projects and taxonomy types. Projects are work
initiatives that belong to products. Taxonomy types define classification
categories (e.g., Backend, Frontend, API) shared by projects (for structured
naming like BE-0001) and tasks.
"""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    and_,
    case,
    literal,
    select,
    text,
)
from sqlalchemy import (
    Enum as SQLAlchemyEnum,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import column_property, relationship
from sqlalchemy.sql import func

from giljo_mcp.domain.project_status import ProjectStatus

from .base import Base, generate_project_alias, generate_uuid


class TaxonomyType(Base):
    """
    Taxonomy type model - unified taxonomy categories for projects and tasks.

    Each taxonomy type defines an abbreviation (e.g., "BE" for Backend, "FE" for Frontend)
    used to generate project taxonomy aliases (BE-0001, FE-0002a) and to classify tasks.

    Handover 0440a: Initial implementation for project taxonomy system (as ProjectType).
    Phase A (agent-parity, 2026-05): Renamed to TaxonomyType to reflect that the same
    classification table now serves both projects and tasks. Table renamed
    project_types -> taxonomy_types in migration ce_0014.
    """

    __tablename__ = "taxonomy_types"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    # BE-8000c: tenant lookups served by uq_taxonomy_type_abbr (tenant_key,
    # abbreviation) leftmost; no column-level index=True (dropped ix_* twin).
    tenant_key = Column(String(36), nullable=False)
    abbreviation = Column(
        String(4),
        nullable=False,
        comment="2-4 uppercase letter abbreviation (e.g., BE, FE, API)",
    )
    label = Column(String(50), nullable=False, comment="Human-readable label (e.g., Backend, Frontend)")
    color = Column(String(7), nullable=False, default="#607D8B", comment="Hex color for UI display")
    sort_order = Column(Integer, default=0, comment="Display ordering in UI dropdowns")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    projects = relationship("Project", back_populates="project_type")

    __table_args__ = (
        # BE-8000c: idx_taxonomy_type_tenant dropped — leftmost-covered by
        # uq_taxonomy_type_abbr (tenant_key, abbreviation).
        UniqueConstraint("tenant_key", "abbreviation", name="uq_taxonomy_type_abbr"),
        # TSK-9076: backup watermark sweep — MAX(updated_at) per tenant.
        Index("idx_taxonomy_types_tenant_updated", "tenant_key", "updated_at"),
    )

    def __repr__(self) -> str:
        return f"<TaxonomyType(id={self.id}, abbreviation='{self.abbreviation}', label='{self.label}')>"


class Project(Base):
    """
    Project model - work initiatives with vision documents.
    Projects belong to a Product and can be created from Tasks.

    Handover 0073: Enhanced with orchestrator closeout support for project completion tracking.
    Handover 0440a: Added taxonomy fields (project_type_id, series_number, subseries).
    """

    __tablename__ = "projects"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    # BE-3002b: NO callable default on tenant_key. A client-side default here
    # silently mints a phantom tenant for any INSERT that forgot to set it —
    # and INSERTs are the one statement class the tenant guard does not inspect,
    # so such rows become invisible orphaned data. The owning service must
    # resolve and supply a real tenant_key (or raise); a forgotten key must fail
    # loudly, never auto-fill. (PK id keeps its default — PKs must auto-generate.)
    tenant_key = Column(String(36), nullable=False)
    # BE-9437: a project MUST belong to a product (operator ruling, 2026-08-15).
    # NOT NULL is the floor under BE-9411 (creates bind to an explicit product)
    # and BE-9415 (conversions bind to the task's own product): those closed the
    # paths that CHOSE a product, this closes the possibility of having none.
    product_id = Column(String(36), ForeignKey("products.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(255), nullable=False)
    alias = Column(
        String(6),
        nullable=False,
        unique=True,
        index=True,
        default=generate_project_alias,
        comment="6-character alphanumeric project identifier (e.g., A1B2C3)",
    )

    # Human-written project description (Handover 0062)
    description = Column(Text, nullable=False)

    # Mission statement (AI-generated by orchestrator)
    mission = Column(Text, nullable=False)
    # Project lifecycle status. Backed by the Postgres ENUM ``project_status``
    # created by migration ce_0008_project_status_enum (BE-5039 Phase 2a).
    # Canonical members: INACTIVE, ACTIVE, COMPLETED, CANCELLED, TERMINATED,
    # DELETED -- declared in giljo_mcp.domain.project_status.ProjectStatus.
    #
    # ``create_type=True`` (SQLAlchemy default) lets ``Base.metadata.create_all``
    # create the type when used in test setup -- the production CE chain
    # uses migration ``ce_0008_project_status_enum`` instead, which is
    # guarded by ``IF NOT EXISTS`` so the two paths cannot conflict.
    # ``values_callable`` writes the .value strings (not the member names)
    # to the DB; ``native_enum=True`` is the Postgres default.
    status = Column(
        SQLAlchemyEnum(
            ProjectStatus,
            name="project_status",
            native_enum=True,
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        default=ProjectStatus.INACTIVE,
        server_default=text("'inactive'::project_status"),
    )

    # Handover 0108: Staging workflow status tracking
    staging_status = Column(
        String(50),
        nullable=True,
        comment="Staging workflow status: null (not staged), staging (in progress), or staging_complete",
    )

    # Handover 0440a: Project taxonomy fields
    project_type_id = Column(
        String(36),
        ForeignKey("taxonomy_types.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to taxonomy_types for taxonomy classification",
    )
    series_number = Column(
        Integer,
        nullable=True,
        comment="Sequential number within a project type (e.g., 1 in BE-0001)",
    )
    subseries = Column(
        String(1),
        nullable=True,
        comment="Single-letter subseries suffix (e.g., 'a' in BE-0001a)",
    )

    # CE-OPT-4: UI visibility flag (hidden projects excluded from default list view)
    # BE-2002: user-facing name is "Archived" in the dashboard/UI; the backend
    # field, param, and DB column stay `hidden` (do not rename).
    hidden = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Whether project is hidden from default list view",
    )

    # BE-9157: audit-trail pointer to the project that supersedes this one. Set
    # when a project is marked ``superseded`` (its work was replaced/consolidated
    # into the successor). Self-referential FK; ON DELETE SET NULL so deleting the
    # successor clears the pointer rather than orphaning it. Nullable — only
    # superseded projects carry a successor. Within-tenant: the owning service
    # validates the successor belongs to the same tenant before writing (the FK
    # itself is not tenant-scoped). Backed by migration ce_0078.
    successor_project_id = Column(
        String(36),
        ForeignKey("projects.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to the project that supersedes this one (audit trail for replaced work)",
    )

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    implementation_launched_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when user clicked Implement button. NULL = staging only.",
    )
    ever_launched_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment=(
            "First time this project EVER crossed the Implement gate. Set once, "
            "never overwritten by re-launch. Survives restage (audit-preserving); "
            "cleared only by reset_to_prestage (discard-everything rewind). Powers "
            "the BE-9085 pre-launch-workproduct detector's restage false-positive "
            "suppression."
        ),
    )
    deleted_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when project was soft deleted (NULL for active projects)",
    )
    cancellation_reason = Column(Text, nullable=True, comment="Reason for project cancellation")
    early_termination = Column(
        Boolean,
        nullable=True,
        default=False,
        server_default=text("false"),
        comment="Whether project was terminated early via termination prompt",
    )

    # Handover 0073: Orchestrator closeout support
    orchestrator_summary = Column(
        Text, nullable=True, comment="AI-generated final summary of project outcomes and deliverables"
    )
    closeout_prompt = Column(
        Text, nullable=True, comment="Prompt template used by orchestrator for closeout generation"
    )
    closeout_executed_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when closeout workflow was executed"
    )
    closeout_checklist = Column(
        JSONB,
        default=list,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        comment="Structured checklist of closeout tasks (JSONB array)",
    )

    # Handover 0260: Execution mode for Claude Code CLI toggle persistence.
    # NULL-state redesign: execution_mode is NULL until the user explicitly picks
    # one. NULL means "not chosen yet" — a first-class, GATED state. It must NEVER
    # silently coerce to 'multi_terminal' (that silent default shipped the wrong
    # orchestration mode). No Python/server default; nullable. The boundary gates
    # at prompt generation, spawn_job, get_staging_instructions and
    # get_job_mission reject a NULL before any protocol rendering, so the
    # HO1020 render-layer fail-safes never see NULL.
    execution_mode = Column(
        String(20),
        nullable=True,
        comment=(
            "Execution mode: 'multi_terminal' | 'claude_code_cli' | 'codex_cli' | "
            "'gemini_cli' | 'antigravity_cli'; NULL = not yet selected"
        ),
    )

    # Handover 0904: Orchestrator auto check-in settings (multi-terminal only)
    auto_checkin_enabled = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Enable orchestrator self-polling in multi-terminal mode",
    )
    auto_checkin_interval = Column(
        Integer,
        nullable=False,
        default=10,
        server_default=text("10"),
        comment="Auto check-in interval in minutes (5, 10, 15, 20, 30, 40, 60)",
    )

    # Relationships
    product = relationship("Product", back_populates="projects")
    project_type = relationship("TaxonomyType", back_populates="projects")
    agent_jobs_v2 = relationship("AgentJob", back_populates="project", cascade="all, delete-orphan")  # Handover 0366a
    messages = relationship("Message", back_populates="project", cascade="all, delete-orphan")
    tasks = relationship(
        "Task", foreign_keys="Task.project_id", back_populates="project", cascade="all, delete-orphan"
    )  # Specify FK to avoid ambiguity
    memory_entries = relationship("ProductMemoryEntry", back_populates="project")  # Handover 0390a

    __table_args__ = (
        # Partial unique index: only enforces uniqueness on active (non-deleted) rows.
        # Allows re-use of taxonomy combinations after soft-deleting a project.
        #
        # BE-9429: postgresql_nulls_not_distinct is LOAD-BEARING, not decoration.
        # project_type_id and subseries are NULL on ordinary rows, and under
        # Postgres' default (NULLS DISTINCT) a NULL anywhere in the tuple makes
        # the row unique by construction -- so without this flag the index does
        # not constrain the common case at all. Every migration that creates it
        # ships NULLS NOT DISTINCT (baseline_v38_unified.py, baseline_v37_unified.py,
        # and the historical fix_taxonomy_nulls_not_distinct), but the flag was
        # missing HERE -- and since the pytest schema is built by
        # Base.metadata.create_all(), that made every test database weaker than
        # every migrated one. No migration accompanies this fix: the migrated
        # shape was already correct and it is the model that was catching up.
        # Pinned by tests/integration/migrations/test_be9429_index_parity.py.
        Index(
            "uq_project_taxonomy_active",
            "tenant_key",
            "product_id",
            "project_type_id",
            "series_number",
            "subseries",
            unique=True,
            postgresql_nulls_not_distinct=True,
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index("idx_project_tenant", "tenant_key"),
        # TSK-9076: backup watermark sweep — MAX(updated_at) per tenant.
        Index("idx_projects_tenant_updated", "tenant_key", "updated_at"),
        Index("idx_project_status", "status"),
        # BE-8000c: ce_0046 perf index for paginated "recent projects for tenant"
        # reads — now declared on the model so autogenerate stops flagging it.
        Index(
            "idx_projects_tenant_created",
            "tenant_key",
            text("created_at DESC"),
            postgresql_where=text("deleted_at IS NULL"),
        ),
        # Handover 0070: Soft delete support
        Index("idx_projects_deleted_at", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        # Handover 0073: Closeout support
        Index(
            "idx_projects_closeout_executed",
            "closeout_executed_at",
            postgresql_where=text("closeout_executed_at IS NOT NULL"),
        ),
        # Single active project per product constraint (Handover 0050b)
        # Ensures only ONE project can be active per product at any time
        Index(
            "idx_project_single_active_per_product",
            "product_id",
            unique=True,
            postgresql_where=text("status = 'active'"),
        ),
    )

    def __repr__(self) -> str:
        return f"<Project(id={self.id}, name='{self.name}', product_id='{self.product_id}')>"


# BE-5058: ``taxonomy_alias`` is a SELECT-time correlated expression so sync
# consumers can read it on a project fetched without ``joinedload(project_type)``
# without triggering an async lazy load (the prior ``@property`` form crashed
# as MissingGreenlet from non-greenlet contexts). The correlated subquery is
# tenant-scoped to keep the model layer's defense-in-depth boundary intact.
_project_abbr_subq = (
    select(TaxonomyType.abbreviation)
    .where(
        TaxonomyType.id == Project.project_type_id,
        TaxonomyType.tenant_key == Project.tenant_key,
    )
    .correlate(Project)
    .scalar_subquery()
)

Project.taxonomy_alias = column_property(
    case(
        (
            and_(Project.project_type_id.is_(None), Project.series_number.is_(None)),
            Project.alias,
        ),
        (
            Project.series_number.is_(None),
            func.coalesce(_project_abbr_subq, literal("")),
        ),
        else_=(
            func.coalesce(_project_abbr_subq, literal(""))
            + case(
                # BE-6079 (L4): key the separator on a NON-EMPTY abbreviation, not
                # merely a non-NULL one. ``nullif(abbr, '')`` collapses an
                # empty-string abbr to NULL so an unabbreviated row renders
                # ``0017`` (no leading dash) exactly as format_taxonomy_alias does
                # (``sep = "-" if abbr else ""``). Theoretical today (abbreviations
                # are regex-gated non-empty) but keeps the two builders in parity.
                (func.nullif(_project_abbr_subq, literal("")).is_not(None), literal("-")),
                else_=literal(""),
            )
            # BE-6049a: pad to a MINIMUM of 4 digits; never truncate. The old
            # fixed width 4 made lpad mangle 5-digit serials (10000 -> "1000").
            # Mirrors utils.taxonomy_alias.format_taxonomy_alias (parity-tested).
            + func.lpad(
                func.cast(Project.series_number, String),
                func.greatest(literal(4), func.length(func.cast(Project.series_number, String))),
                literal("0"),
            )
            + func.coalesce(Project.subseries, literal(""))
        ),
    ),
    deferred=False,
)
