# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.

"""
Security Headers Middleware

Adds production-grade security headers to all responses.

Created in Handover 0129c - Security Hardening & OWASP Compliance
Updated in Handover 1007 - Hash-Based CSP Implementation
Updated: Dynamic CSP connect-src includes external_host when configured
"""

import logging
import os
from pathlib import Path

from starlette.datastructures import MutableHeaders
from starlette.requests import Request
from starlette.types import ASGIApp, Message, Receive, Scope, Send


logger = logging.getLogger(__name__)

# CSP hashes for inline code blocks in frontend/index.html
# Generated by scripts/generate_csp_hashes.py
# Regenerate if inline code changes
CSP_STYLE_HASH = "'sha256-pR5eQD+pcfGctW0ZvPpp3UToUJkVDBclZbDZVJBZoBU='"  # Loading animation styles
CSP_SCRIPT_HASH_1 = "'sha256-LRJOHmw/kARrWFQNFXTam7BNVjtucN2V1FzuxKtEUg0='"  # API URL configuration (INF-5012c)
CSP_SCRIPT_HASH_2 = "'sha256-T+y4FnL+BP2aiGWNs6H5HdyLosVMnGaNc9v+5DaNNJM='"  # Splash screen logic

_EXTRA_CSP_SCRIPT_HASHES: set[str] = set()
_EXTRA_CSP_STYLE_HASHES: set[str] = set()
_EXTRA_CSP_STYLE_ORIGINS: set[str] = set()
_EXTRA_CSP_SCRIPT_ORIGINS: set[str] = set()
_EXTRA_CSP_CONNECT_ORIGINS: set[str] = set()
_EXTRA_CSP_FRAME_ORIGINS: set[str] = set()
_EXTRA_CSP_PAYMENT_ORIGINS: set[str] = set()
_ALLOW_EXTRA_STYLE_ATTRS: list[bool] = [False]


def register_csp_sources(
    *,
    script_hashes: list[str] | tuple[str, ...] = (),
    style_hashes: list[str] | tuple[str, ...] = (),
    style_origins: list[str] | tuple[str, ...] = (),
    script_origins: list[str] | tuple[str, ...] = (),
    connect_origins: list[str] | tuple[str, ...] = (),
    frame_origins: list[str] | tuple[str, ...] = (),
    payment_origins: list[str] | tuple[str, ...] = (),
    allow_style_attrs: bool = False,
) -> None:
    """Allow private edition modules to register additional CSP sources."""
    _EXTRA_CSP_SCRIPT_HASHES.update(_clean_values(script_hashes))
    _EXTRA_CSP_STYLE_HASHES.update(_clean_values(style_hashes))
    _EXTRA_CSP_STYLE_ORIGINS.update(_clean_values(style_origins))
    _EXTRA_CSP_SCRIPT_ORIGINS.update(_clean_values(script_origins))
    _EXTRA_CSP_CONNECT_ORIGINS.update(_clean_values(connect_origins))
    _EXTRA_CSP_FRAME_ORIGINS.update(_clean_values(frame_origins))
    _EXTRA_CSP_PAYMENT_ORIGINS.update(_clean_values(payment_origins))
    _ALLOW_EXTRA_STYLE_ATTRS[0] = _ALLOW_EXTRA_STYLE_ATTRS[0] or allow_style_attrs


def clear_registered_csp_sources_for_tests() -> None:
    """Reset registered CSP extensions for isolated tests."""
    _EXTRA_CSP_SCRIPT_HASHES.clear()
    _EXTRA_CSP_STYLE_HASHES.clear()
    _EXTRA_CSP_STYLE_ORIGINS.clear()
    _EXTRA_CSP_SCRIPT_ORIGINS.clear()
    _EXTRA_CSP_CONNECT_ORIGINS.clear()
    _EXTRA_CSP_FRAME_ORIGINS.clear()
    _EXTRA_CSP_PAYMENT_ORIGINS.clear()
    _ALLOW_EXTRA_STYLE_ATTRS[0] = False


def _clean_values(values: list[str] | tuple[str, ...]) -> list[str]:
    return [value.strip() for value in values if value and value.strip()]


def _frontend_dist_built() -> bool:
    """Mirror startup.py's own production/development signal.

    startup.py labels its console banner PRODUCTION exactly when
    frontend/dist/index.html exists (the operator chose "Production" at the
    installer's frontend-mode prompt and no Vite dev server is running).
    """
    return (Path.cwd() / "frontend" / "dist" / "index.html").exists()


def is_development_mode() -> bool:
    """
    Detect if running in development mode.

    Checks (in order):
    1. GILJO_ENV environment variable (dev/development) -- explicit override,
       always trusted as-is.
    2. ENVIRONMENT environment variable (dev/development) -- installer/core/
       config.py's generated .env stamps ENVIRONMENT=development on every CE
       install regardless of the Production-vs-Contributor frontend-mode
       choice made later in the install flow (TSK-9123), so this value alone
       can't be trusted for that ambiguous case: fall back to the same
       frontend/dist/index.html signal startup.py's console banner uses, so
       a "Production" install serves the hardened CSP its banner claims, and
       a "Contributor / Dev mode" install (Vite dev server, no dist/) keeps
       the unsafe-eval relaxation Vite HMR needs.
    3. Default to production (fail-safe)

    Returns:
        True if development mode, False for production
    """
    env = os.getenv("GILJO_ENV", "").lower()
    if env in ("dev", "development"):
        return True

    env = os.getenv("ENVIRONMENT", "").lower()
    if env in ("dev", "development"):
        return not _frontend_dist_built()

    return False


class SecurityHeadersMiddleware:
    """
    Middleware to add security headers to all responses.

    Headers added:
    - Strict-Transport-Security (HSTS): Enforce HTTPS
    - Content-Security-Policy (CSP): Prevent XSS (hash-based, no unsafe-inline)
    - X-Frame-Options: Prevent clickjacking
    - X-Content-Type-Options: Prevent MIME sniffing
    - Referrer-Policy: Control referrer information
    - Permissions-Policy: Control browser features
    - X-XSS-Protection: Legacy XSS protection

    All headers follow OWASP security best practices.

    CSP Implementation (Handover 1007):
    - Uses SHA-256 hashes for inline scripts and styles
    - Production: No unsafe-inline or unsafe-eval
    - Development: Allows unsafe-eval for HMR (Hot Module Replacement)
    - Hashes are calculated from exact content in frontend/index.html
    """

    def __init__(self, app: ASGIApp, hsts_max_age: int = 31536000):
        """
        Initialize security headers middleware.

        Args:
            app: FastAPI application instance
            hsts_max_age: HSTS max-age in seconds (default: 1 year)
        """
        self.app = app
        self.hsts_max_age = hsts_max_age
        self.is_dev = is_development_mode()

        # Read external_host and port from config for dynamic CSP connect-src
        self.external_host = None
        self.api_port = None
        self.ssl_enabled = False
        try:
            from giljo_mcp.config_manager import get_config

            config = get_config()
            self.external_host = config.get_nested("services.external_host", default=None)
            self.api_port = config.get_nested("services.api.port", default=config.server.api_port)
            self.ssl_enabled = config.get_nested("features.ssl_enabled", default=False)
        except (ImportError, AttributeError, KeyError, TypeError):
            logger.debug("Config not available for CSP — using defaults")

        # Sentry ingest origins for connect-src (INF-5070).
        # The frontend @sentry/vue SDK POSTs events directly to the Sentry
        # ingest endpoint derived from the DSN host. Without this entry the
        # browser blocks the request before egress, making frontend error
        # tracking silently non-functional. Gated by GILJO_MODE so CE keeps
        # the tighter CSP — CE never has a Sentry DSN configured. Parsing
        # from the DSN env vars (rather than hard-coding *.ingest.sentry.io)
        # keeps cross-region (us/eu) and account-migration scenarios working
        # without a code change.
        self.sentry_origins: list[str] = self._compute_sentry_origins()
        if self.sentry_origins:
            logger.info(f"CSP: sentry ingest allowlisted in connect-src: {self.sentry_origins}")

        mode_str = "DEVELOPMENT" if self.is_dev else "PRODUCTION"
        logger.info(f"SecurityHeadersMiddleware initialized in {mode_str} mode")
        logger.info(f"HSTS max-age: {hsts_max_age}s")

        if self.is_dev:
            logger.warning("CSP: unsafe-eval enabled for development HMR")

    @staticmethod
    def _compute_sentry_origins() -> list[str]:
        """Parse SENTRY_DSN_* env vars and return scheme+host origins for CSP.

        Returns an empty list when GILJO_MODE != saas or when no DSN is
        set. Each returned origin is the bare scheme://host (no userinfo, no
        port, no path) suitable for direct concatenation into a CSP allowlist.
        """
        from api.app_state import GILJO_MODE

        if GILJO_MODE != "saas":
            return []
        from urllib.parse import urlparse

        origins: list[str] = []
        for var in ("SENTRY_DSN_BACKEND", "SENTRY_DSN_FRONTEND"):
            dsn = os.getenv(var, "").strip()
            if not dsn:
                continue
            try:
                parsed = urlparse(dsn)
            except ValueError:
                continue
            if parsed.scheme not in ("http", "https"):
                continue
            if not parsed.hostname:
                continue
            origin = f"{parsed.scheme}://{parsed.hostname}"
            if origin not in origins:
                origins.append(origin)
        return origins

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        """Add security headers to the response on the ``http.response.start`` message.

        Pure-ASGI (BE-6063c): wraps ``send`` so headers are injected on every
        response — including error responses and streaming/SSE bodies — exactly
        as the prior BaseHTTPMiddleware version mutated ``response.headers``. The
        body stream is forwarded untouched (no buffering/replay), preserving
        /mcp SSE pass-through.
        """
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request = Request(scope, receive)

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                self._apply_security_headers(MutableHeaders(raw=message["headers"]), request, message["status"])
            await send(message)

        await self.app(scope, receive, send_with_headers)

    def _apply_security_headers(self, response_headers: MutableHeaders, request: Request, status: int) -> None:
        """Inject the OWASP/CSP header set into ``response_headers`` in place.

        ``MutableHeaders`` supports ``__setitem__`` (overwrite), ``.get()`` and
        key iteration — the exact subset the prior ``response.headers`` logic
        used — so the directive-build logic below is byte-for-byte identical to
        the BaseHTTPMiddleware version.
        """
        # HSTS: Only add for HTTPS connections (meaningless for HTTP)
        if request.url.scheme == "https":
            response_headers["Strict-Transport-Security"] = f"max-age={self.hsts_max_age}; includeSubDomains; preload"

        # CSP: Hash-based policy preventing XSS
        # Production: Strict hashes only
        # Development: Hashes + unsafe-eval for Vue HMR
        # Cloudflare: static.cloudflareinsights.com hosts the auto-injected
        # Browser Insights (RUM) beacon; harmless if you're not behind CF.
        script_hashes = " ".join([CSP_SCRIPT_HASH_1, CSP_SCRIPT_HASH_2, *_EXTRA_CSP_SCRIPT_HASHES])
        script_src = f"'self' {script_hashes} https://static.cloudflareinsights.com"
        if _EXTRA_CSP_SCRIPT_ORIGINS:
            script_src += " " + " ".join(sorted(_EXTRA_CSP_SCRIPT_ORIGINS))
        if self.is_dev:
            script_src += " 'unsafe-eval'"  # Vue HMR needs eval in dev

        # CSP nonce hook (SEC-0021): when SaaS CspNonceMiddleware sets
        # request.state.csp_nonce, swap 'unsafe-inline' for 'nonce-<X>' in
        # style-src so Vuetify's runtime-injected style tags carry the matching
        # nonce attribute. The static splash <style> block in index.html still
        # needs its SHA-256 hash listed alongside the nonce — CSP3 allows
        # nonce + hash hybrid (an inline style is permitted if it matches the
        # nonce OR any listed hash). Without the hash, the splash CSS is
        # blocked in SaaS and the logo fade-in dies. CE never sets the
        # attribute, so style-src keeps 'unsafe-inline' — CE behavior unchanged.
        nonce = getattr(request.state, "csp_nonce", "")
        style_hashes = " ".join([CSP_STYLE_HASH, *_EXTRA_CSP_STYLE_HASHES])
        style_src = f"'self' 'nonce-{nonce}' {style_hashes}" if nonce else "'self' 'unsafe-inline'"
        if _EXTRA_CSP_STYLE_ORIGINS:
            style_src += " " + " ".join(sorted(_EXTRA_CSP_STYLE_ORIGINS))

        # connect-src: 'self' already covers same-origin API/WebSocket calls
        # (the common case). ws: / wss: allow cross-scheme WebSocket to the
        # same host. Building additional explicit host:port entries from config
        # was historically used for "defense-in-depth" but actively broke
        # reverse-proxy deployments (Cloudflare Tunnel): when the config held
        # external_host=mcp.example.com + api_port=7272, CSP allowed
        # `http://mcp.example.com:7272` while the browser loaded via
        # `https://mcp.example.com` — rejecting the frontend's real API calls.
        # (INF-5012b close-out.)
        # cloudflareinsights.com is the beacon endpoint paired with the
        # static.cloudflareinsights.com script source above.
        connect_src = "'self' ws: wss: https://cloudflareinsights.com"
        if self.sentry_origins:
            connect_src += " " + " ".join(self.sentry_origins)
        if _EXTRA_CSP_CONNECT_ORIGINS:
            connect_src += " " + " ".join(sorted(_EXTRA_CSP_CONNECT_ORIGINS))

        frame_src = "'self'"
        if _EXTRA_CSP_FRAME_ORIGINS:
            frame_src += " " + " ".join(sorted(_EXTRA_CSP_FRAME_ORIGINS))

        # style-src-attr: hosted-checkout SDKs assign inline element.style at
        # runtime to size/position their iframes. CSP3 splits style governance:
        # style-src controls BOTH stylesheet elements AND inline style
        # attributes unless overridden via style-src-elem / style-src-attr.
        # Keep style-src strict for stylesheets (billing CDN allowlist) and
        # relax ONLY the attribute case for SaaS so the checkout SDK's
        # runtime DOM style assignments apply. CE stays fully strict (no
        # style-src-attr directive at all → falls back to style-src → inline
        # attributes blocked).
        style_src_attr_directive = "style-src-attr 'unsafe-inline'; " if _ALLOW_EXTRA_STYLE_ATTRS[0] else ""

        response_headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            f"script-src {script_src}; "
            f"style-src {style_src}; "
            f"{style_src_attr_directive}"
            "img-src 'self' data: https:; "
            "font-src 'self' data:; "
            f"connect-src {connect_src}; "
            f"frame-src {frame_src}; "
            "frame-ancestors 'none'; "  # No embedding
            "base-uri 'self'; "
            "form-action 'self'"
        )

        # X-Frame-Options: Prevent clickjacking
        response_headers["X-Frame-Options"] = "DENY"

        # X-Content-Type-Options: Prevent MIME sniffing
        response_headers["X-Content-Type-Options"] = "nosniff"

        # Referrer-Policy: Limit referrer information
        response_headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions-Policy: Disable unnecessary features.
        payment_policy = "payment=()"
        if _EXTRA_CSP_PAYMENT_ORIGINS:
            origins = " ".join(f'"{o}"' for o in sorted(_EXTRA_CSP_PAYMENT_ORIGINS))
            payment_policy = f"payment=(self {origins})"
        response_headers["Permissions-Policy"] = (
            "geolocation=(), "
            "microphone=(), "
            "camera=(), "
            f"{payment_policy}, "
            "usb=(), "
            "magnetometer=(), "
            "gyroscope=(), "
            "accelerometer=()"
        )

        # X-XSS-Protection: Legacy XSS protection (deprecated but harmless)
        response_headers["X-XSS-Protection"] = "1; mode=block"

        # Cache-Control: prevent stale index.html from referencing rebuilt
        # asset bundles. Vite emits content-hashed filenames under /assets/*
        # (e.g. main-DxIqQVpb.js) — those are safe to cache forever. But
        # index.html points at the *current* hashes; if a browser caches an
        # old index.html after a rebuild, it requests bundles that no longer
        # exist, the SPA 404 fallback returns index.html (text/html), and the
        # browser refuses to execute HTML as a JS module. Result: blank page
        # until hard-refresh. Force revalidation of HTML, cache hashed assets.
        #
        # SEC-9454: the long-lived policy describes the BODY we are sending, so
        # it may only follow a response that actually carries the asset. During
        # a deploy the new hashed filename does not exist yet; api/app.py's SPA
        # fallback correctly 404s it (FE-6120) rather than returning index.html.
        # Stamping that 404 immutable told every edge to serve the miss for up to
        # a year, turning a brief deploy window into an extended outage that only
        # a manual cache purge could end. Errors on this path get `no-store`.
        path = request.url.path
        is_asset = path.startswith("/assets/")
        # 2xx carries the asset; 304 is a revalidated HIT and must keep the same
        # policy a 200 would have (RFC 7232) — `no-store` there would tell the
        # browser to discard the copy it just confirmed fresh. Everything else,
        # including a 3xx redirect, is not the asset and must not outlive it.
        serves_the_asset = 200 <= status < 300 or status == 304

        if is_asset and not serves_the_asset:
            # Set unconditionally: an error response must never be long-cached,
            # whoever set the header.
            response_headers["Cache-Control"] = "no-store"
        elif "cache-control" not in (h.lower() for h in response_headers):
            if is_asset:
                response_headers["Cache-Control"] = "public, max-age=31536000, immutable"
            else:
                content_type = response_headers.get("content-type", "")
                if content_type.startswith("text/html"):
                    response_headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
                    response_headers["Pragma"] = "no-cache"
                    response_headers["Expires"] = "0"
