# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.


import importlib.util
import subprocess
from pathlib import Path

import pytest


_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "check_no_ai_signatures.py"

pytestmark = pytest.mark.skipif(
    not _SCRIPT.exists(),
    reason="scripts/check_no_ai_signatures.py is stripped from the CE export artifact",
)

_BAD_TRAILER = "Co-Authored" + "-By: Release Bot <bot@example.invalid>"


def _load_module():
    spec = importlib.util.spec_from_file_location("check_no_ai_signatures", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _git(repo: Path, *args: str, env: dict) -> None:
    subprocess.run(
        ["git", *args],
        cwd=str(repo),
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )


def _make_repo(tmp_path: Path) -> tuple[Path, dict]:
    repo = tmp_path / "repo"
    repo.mkdir()

    import os

    empty_cfg = tmp_path / "empty.gitconfig"
    empty_cfg.write_text("", encoding="utf-8")
    env = dict(os.environ)
    env["GIT_CONFIG_GLOBAL"] = str(empty_cfg)
    env["GIT_CONFIG_SYSTEM"] = str(empty_cfg)

    common = ["-c", "user.name=Tester", "-c", "user.email=tester@example.invalid", "-c", "commit.gpgsign=false"]
    _git(repo, "init", env=env)
    (repo / "f.txt").write_text("v1\n", encoding="utf-8")
    _git(repo, "add", "f.txt", env=env)
    _git(repo, *common, "commit", "--no-verify", "-m", "init", env=env)

    (repo / "f.txt").write_text("v2\n", encoding="utf-8")
    _git(repo, "add", "f.txt", env=env)
    _git(repo, *common, "commit", "--no-verify", "-m", "BE-0001: clean change\n\n**Edition Scope:** Both", env=env)

    (repo / "f.txt").write_text("v3\n", encoding="utf-8")
    _git(repo, "add", "f.txt", env=env)
    _git(repo, *common, "commit", "--no-verify", "-m", f"BE-0002: tainted change\n\n{_BAD_TRAILER}", env=env)

    return repo, env


def test_range_flags_planted_signature(tmp_path, monkeypatch, capsys):
    mod = _load_module()
    repo, env = _make_repo(tmp_path)
    monkeypatch.chdir(repo)

    bad_sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=str(repo), env=env, text=True).strip()

    rc = mod._check_commit_range("HEAD~1..HEAD")

    assert rc == 1
    out = capsys.readouterr().out
    assert bad_sha in out


def test_range_passes_clean_commits(tmp_path, monkeypatch):
    mod = _load_module()
    repo, _env = _make_repo(tmp_path)
    monkeypatch.chdir(repo)

    rc = mod._check_commit_range("HEAD~2..HEAD~1")

    assert rc == 0


def test_commit_msg_file_mode_still_works(tmp_path):
    mod = _load_module()

    dirty = tmp_path / "MSG_DIRTY"
    dirty.write_text(f"subject line\n\n{_BAD_TRAILER}\n", encoding="utf-8")
    assert mod._check_commit_msg_file(str(dirty)) == 1

    clean = tmp_path / "MSG_CLEAN"
    clean.write_text("BE-0003: ordinary subject\n\n**Edition Scope:** CE\n", encoding="utf-8")
    assert mod._check_commit_msg_file(str(clean)) == 0


def test_range_requires_argument():
    mod = _load_module()
    import sys

    saved = sys.argv
    try:
        sys.argv = ["check_no_ai_signatures.py", "--range"]
        assert mod.main() == 1
    finally:
        sys.argv = saved


def test_built_with_model_is_flagged():
    mod = _load_module()
    assert mod.find_signature("Add feature\n\n" + "Built " + "with Claude") is not None
    assert mod.find_signature("Refactor: built with care by the team") is None


def test_parity_full_model_list_caught():
    mod = _load_module()
    coauth = "Co-Authored" + "-By: "
    assert mod.find_signature("subj\n\n" + coauth + "Sonnet <x@y.invalid>") is not None
    assert mod.find_signature("subj\n\n" + coauth + "Cursor <x@y.invalid>") is not None
    assert mod.find_signature("subj\n\n" + coauth + "Opus <x@y.invalid>") is not None
    assert mod.find_signature("subj\n\nGenerated by Opus") is not None
    assert mod.find_signature("subj\n\nGenerated by Anthropic tooling") is not None


def test_bare_model_word_not_flagged():
    mod = _load_module()
    assert mod.find_signature("Refactor opus module and tidy haiku formatting") is None
    assert mod.find_signature("Generated with airflow scheduler config") is None
