# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# [CE] Community Edition.

"""
Python-based validation tests for install.ps1.

These tests verify structural properties of the PowerShell installer
without requiring Pester or PowerShell execution. They run as part of
the standard pytest suite.
"""

import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
INSTALL_PS1 = REPO_ROOT / "scripts" / "install.ps1"
START_BAT = REPO_ROOT / "scripts" / "start-giljoai.bat"


class TestInstallPs1Exists:
    """Verify the installer script file exists and is non-empty."""

    def test_script_file_exists(self):
        assert INSTALL_PS1.exists(), f"Expected {INSTALL_PS1} to exist"

    def test_script_is_not_empty(self):
        content = INSTALL_PS1.read_text(encoding="utf-8")
        assert len(content) > 100, "install.ps1 appears to be empty or truncated"


class TestInstallPs1Structure:
    """Verify the script contains required structural elements."""

    @pytest.fixture(autouse=True)
    def _load_content(self):
        self.content = INSTALL_PS1.read_text(encoding="utf-8")

    def test_requires_directive(self):
        assert "#Requires -Version 5.1" in self.content

    def test_error_action_preference(self):
        assert "$ErrorActionPreference = 'Stop'" in self.content

    def test_has_install_dir_parameter(self):
        assert "[string]$InstallDir" in self.content

    def test_has_skip_prereqs_parameter(self):
        assert "[switch]$SkipPrereqs" in self.content

    def test_has_update_parameter(self):
        assert "[switch]$Update" in self.content

    def test_phase_1_prerequisites(self):
        assert "function Test-Prerequisites" in self.content

    def test_phase_2_download(self):
        assert "function Get-LatestRelease" in self.content

    def test_phase_3_environment(self):
        assert "function Initialize-Environment" in self.content

    def test_phase_4_install_py(self):
        assert "function Invoke-InstallPy" in self.content

    def test_install_py_uses_setup_only_flag(self):
        assert "--setup-only" in self.content

    def test_phase_5_shortcuts(self):
        assert "function Install-Shortcuts" in self.content

    def test_phase_6_completion(self):
        assert "function Show-Completion" in self.content

    def test_main_wrapper_function(self):
        assert "function Invoke-GiljoInstaller" in self.content

    def test_github_repo_reference(self):
        assert "giljoai/giljo-hq" in self.content

    def test_sha256_verification(self):
        assert "Get-FileHash" in self.content
        assert "SHA256" in self.content

    def test_winget_package_ids(self):
        assert "Python.Python.3.12" in self.content
        assert "OpenJS.NodeJS.LTS" in self.content
        assert "Git.Git" in self.content

    def test_no_ai_signatures(self):
        lowered = self.content.lower()
        assert "co-authored-by" not in lowered
        assert "generated by" not in lowered

    def test_no_saas_references(self):
        assert "GILJO_MODE=saas" not in self.content
        assert "saas/" not in self.content.lower()

    def test_license_header(self):
        assert "Elastic License 2.0" in self.content


@pytest.mark.skipif(sys.platform != "win32", reason="PowerShell syntax check only runs on Windows")
class TestInstallPs1Syntax:
    """Validate PowerShell syntax if PowerShell is available."""

    def test_powershell_parses_without_errors(self):
        """Use PowerShell's parser to check for syntax errors."""
        ps_check = (
            f"$errors = $null; "
            f"[System.Management.Automation.Language.Parser]::ParseFile("
            f"'{INSTALL_PS1}', [ref]$null, [ref]$errors); "
            f"if ($errors.Count -gt 0) {{ "
            f"$errors | ForEach-Object {{ Write-Error $_.Message }}; "
            f"exit 1 }} else {{ exit 0 }}"
        )
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", ps_check],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        assert result.returncode == 0, f"PowerShell syntax errors in install.ps1:\n{result.stderr}"


class TestStartBat:
    """Verify the start-giljoai.bat launcher script (INF-9321 contract).

    The pre-INF-9321 version of this class pinned the DRIFTED launcher:
    it asserted `activate.bat` and `api.run_api` were present -- the exact
    pattern check_installer_integrity.py forbids in install.ps1's heredoc --
    and its `api.run_api` assertion kept passing against the fixed bat by
    matching a COMMENT. These tests now pin the corrected contract, and the
    behavioural asserts look only at CODE lines (comments stripped) so prose
    can never satisfy or violate them again.
    """

    @staticmethod
    def _code_lines() -> list[str]:
        content = START_BAT.read_text(encoding="utf-8")
        return [line for line in content.splitlines() if line.strip() and not line.strip().upper().startswith("REM ")]

    def test_bat_file_exists(self):
        assert START_BAT.exists(), f"Expected {START_BAT} to exist"

    def test_bat_has_echo_off(self):
        content = START_BAT.read_text(encoding="utf-8")
        assert "@echo off" in content

    def test_bat_launches_startup_py_with_the_venv_python(self):
        """The launcher must run venv\\Scripts\\python.exe startup.py -- never a
        bare `python` (the Store alias trap) and never api.run_api (skips
        migrations, frontend build, and the browser open)."""
        code = self._code_lines()
        assert any("venv\\Scripts\\python.exe" in line and "startup.py" in line for line in code), code

    def test_bat_never_invokes_run_api_or_activate_in_code(self):
        """The drifted launcher used `call activate.bat` + `python -m api.run_api`."""
        code = self._code_lines()
        assert not any("api.run_api" in line for line in code), code
        assert not any("activate.bat" in line for line in code), code

    def test_bat_cds_to_the_install_root(self):
        """The bat ships inside scripts/ but venv + startup.py live one level up."""
        code = self._code_lines()
        assert any('cd /d "%~dp0..' in line for line in code), code
