<template>
  <v-container>
    <v-row class="align-center mb-4 main-window-reveal main-window-reveal--hero main-window-delay-1">
      <v-col>
        <h1 class="text-headline-large">Roadmap</h1>
        <p class="text-body-medium text-muted-a11y mt-1">
          An AI-prioritized execution plan from this product's inactive projects and pending tasks, each scored for risk and complexity by your AI agent. Drag to reorder, or convert a task into a project. Implementation starts elsewhere — on the Projects page, or from your connected agent.
          <v-tooltip location="bottom start" max-width="600">
            <template #activator="{ props }">
              <v-icon v-bind="props" size="16" class="help-icon">mdi-help-circle-outline</v-icon>
            </template>
            <div>
              <div class="font-weight-bold mb-1">Roadmap Reference</div>
              <div class="text-body-small mb-2 text-muted-a11y">One roadmap per product</div>
              <div><span class="font-weight-medium">Rank:</span> drag the dotted grip to reorder; the new order is saved automatically and survives a refresh.</div>
              <div class="mt-1"><span class="font-weight-medium">Convert (tasks):</span> promotes the task to a project using the standard conversion.</div>
              <div class="mt-2 text-body-small">The ranking, plus each item's risk and complexity, is generated by your AI agent via the roadmap MCP tool. This page orders work; it does not launch it.</div>
            </div>
          </v-tooltip>
        </p>
      </v-col>
    </v-row>

    <v-alert
      v-if="noActiveProduct"
      type="info"
      variant="tonal"
      class="ma-4 main-window-reveal main-window-delay-2"
    >
      No product is open. Add a product to view its roadmap.
    </v-alert>

    <template v-else>
      <div class="filter-bar main-window-reveal main-window-delay-2">
        <span class="rm-product-label">
          <span class="rm-product-dot" :class="{ 'rm-product-dot--off': !activeProduct }"></span>
          {{ activeProduct ? activeProduct.name : 'Active product' }}
        </span>
        <div class="filter-spacer"></div>
        <v-switch
          v-model="foldInTasks"
          label="Fold in tasks"
          color="primary"
          density="compact"
          hide-details
          inset
          class="rm-fold-toggle"
        />
        <RoadmapPromptActions
          :is-empty="isEmptyRoadmap"
          :prompt-text="currentPromptText"
          @copy="copyRoadmapPrompt"
        />
      </div>

      <v-alert
        v-if="waiting"
        type="info"
        variant="tonal"
        density="compact"
        class="rm-waiting main-window-reveal main-window-delay-2"
        closable
        @click:close="dismissWaiting"
      >
        <div class="rm-waiting-row">
          <v-progress-circular indeterminate size="18" width="2" color="primary" class="rm-waiting-spin" />
          <span>
            Waiting for your agent… paste the copied prompt into the agent connected to this account.
            This clears automatically when your agent saves the roadmap.
          </span>
        </div>
      </v-alert>

      <v-alert
        v-if="showInsightBanner"
        type="info"
        variant="tonal"
        density="compact"
        icon="mdi-lightbulb-on-outline"
        class="rm-insight main-window-reveal main-window-delay-2"
      >
        <div class="font-weight-bold mb-1">{{ insightTitle }}</div>
        <div>{{ roadmap.summary }}</div>
      </v-alert>

      <div v-if="loading && items.length === 0" class="rm-loading">
        <v-progress-circular indeterminate color="primary" size="32" />
      </div>

      <v-alert
        v-else-if="items.length === 0"
        type="info"
        variant="tonal"
        class="main-window-reveal main-window-delay-2"
      >
        No roadmap yet. Ask your AI agent to rank this product's inactive projects and pending tasks
        (it writes the roadmap via the <code>save_roadmap</code> MCP tool), then refresh.
      </v-alert>

      <draggable
        v-else
        :model-value="displayItems"
        item-key="id"
        handle=".rm-grip"
        tag="div"
        class="rm-list main-window-reveal main-window-delay-2"
        ghost-class="rm-ghost"
        :animation="180"
        @update:model-value="onListReorder"
      >
        <template #item="{ element, index }">
          <div class="rm-row">
            <RoadmapCard
              :item="element"
              :rank="index + 1"
              :in-chain="sequenceRunStore.isProjectInActiveChain(element.project_id)"
              @convert="convertTask"
              @open="openItem"
              @demote="demote"
              @remove="removeItem"
            />
          </div>
        </template>
      </draggable>
    </template>

    <ProjectCreateEditDialog
      ref="projectDialogRef"
      v-model="showProjectDialog"
      :editing-project="editingProject"
      :active-product="activeProduct"
      :project-types="projectTypes"
      @saved="onProjectSaved"
      @clear-mission="showClearMissionDialog = true"
      @type-created="onTypeCreated"
    />

    <BaseDialog
      v-model="showClearMissionDialog"
      type="warning"
      title="Clear Mission?"
      confirm-label="Clear"
      size="sm"
      @confirm="onClearMissionConfirmed"
      @cancel="showClearMissionDialog = false"
    >
      <p>Clear the mission? It will be regenerated on next staging.</p>
    </BaseDialog>

    <TaskEditDialog
      v-model="showTaskDialog"
      :editing-task="editingTask"
      :current-task="currentTask"
      :saving="saving"
      :status-select-options="TASK_STATUS_OPTIONS"
      :task-type-options="taskTypeOptions"
      @cancel="cancelTask"
      @save="onTaskSave"
      @update:current-task="onCurrentTaskUpdate"
    />

    <BaseDialog
      v-model="showConvertConfirm"
      type="info"
      title="Convert to Project"
      icon="mdi-folder-arrow-up"
      confirm-label="Convert"
      @confirm="confirmConvert"
      @cancel="showConvertConfirm = false"
    >
      <p class="text-body-large mb-2">
        Convert task <strong>"{{ conversionItem?.title }}"</strong> to a project?
      </p>
      <p class="text-body-medium text-muted-a11y">
        This creates a new project in the viewed product from the task's title and description.
      </p>
    </BaseDialog>
  </v-container>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useProductStore } from '@/stores/products'
import { buildRoadmapPrompt as buildRoadmapPromptText } from '@/content/roadmap/prompts'
import { useProjectStore } from '@/stores/projects'
import { useWebSocketStore } from '@/stores/websocket'
import { useSequenceRunStore } from '@/stores/sequenceRunStore'
import { registerReconnectResync } from '@/stores/websocketEventRouter'
import api from '@/services/api'
import { parseErrorResponse } from '@/utils/errorMessages'
import { agentSavedAfter, waitIsSuperseded } from '@/utils/roadmapWaitReconcile'
import { useToast } from '@/composables/useToast'
import { useTaskCrud } from '@/composables/useTaskCrud'
import { useFormatDate } from '@/composables/useFormatDate'
import draggable from 'vuedraggable'
import RoadmapCard from '@/components/RoadmapCard.vue'
import BaseDialog from '@/components/common/BaseDialog.vue'
import RoadmapPromptActions from '@/components/roadmap/RoadmapPromptActions.vue'
import ProjectCreateEditDialog from '@/components/projects/ProjectCreateEditDialog.vue'
import TaskEditDialog from './tasks/TaskEditDialog.vue'

const productStore = useProductStore()
const projectStore = useProjectStore()
const wsStore = useWebSocketStore()
const sequenceRunStore = useSequenceRunStore()
const { showToast } = useToast()
const { formatDate } = useFormatDate()

const TASK_STATUS_OPTIONS = ['pending', 'in_progress', 'on_hold', 'completed', 'blocked', 'cancelled']

const loading = ref(false)
const noActiveProduct = ref(false)
const roadmap = ref(null)
const items = ref([])
const foldInTasks = ref(true)
const projectTypes = ref([])

const activeProduct = computed(() => productStore.currentProduct)
const viewedProductId = computed(() => productStore.currentProduct?.id)
const isEmptyRoadmap = computed(() => items.value.length === 0)

const showInsightBanner = computed(() => !isEmptyRoadmap.value && !!roadmap.value?.summary)
const insightTitle = computed(() => {
  const at = roadmap.value?.last_generated_at
  return at ? `Why this order · ${formatDate(at)}` : 'Why this order'
})

const displayItems = computed(() =>
  foldInTasks.value ? items.value : items.value.filter((it) => it.item_type !== 'task'),
)

const waiting = ref(false)
const isPersisting = ref(false)
let waitingTimeout = null
let refetchDebounce = null
let unsubRoadmap = null
let unsubAgentActive = null
let unsubProjectUpdate = null
let unsubHeadlessLifecycle = []
let unsubResync = null

const WAITING_TIMEOUT_MS = 150000
const REFETCH_DEBOUNCE_MS = 600

const AGENT_ACTIVE_STORAGE_PREFIX = 'giljo.roadmap.agentActiveAt.'

function agentActiveStorageKey() {
  const pid = productStore.effectiveProductId
  return pid ? `${AGENT_ACTIVE_STORAGE_PREFIX}${pid}` : null
}

function persistAgentActive() {
  const key = agentActiveStorageKey()
  if (!key) return
  try {
    localStorage.setItem(key, String(Date.now()))
  } catch {
    /* localStorage unavailable (private mode / quota) — non-fatal */
  }
}

function clearPersistedAgentActive() {
  const key = agentActiveStorageKey()
  if (!key) return
  try {
    localStorage.removeItem(key)
  } catch {
    /* non-fatal */
  }
}

function startWaiting(durationMs = WAITING_TIMEOUT_MS) {
  waiting.value = true
  if (waitingTimeout) clearTimeout(waitingTimeout)
  waitingTimeout = setTimeout(() => {
    waiting.value = false
    waitingTimeout = null
    clearPersistedAgentActive()
  }, durationMs)
}

function dismissWaiting() {
  waiting.value = false
  if (waitingTimeout) {
    clearTimeout(waitingTimeout)
    waitingTimeout = null
  }
  clearPersistedAgentActive()
}

function rehydrateWaitingFromStorage() {
  if (waiting.value) return
  const key = agentActiveStorageKey()
  if (!key) return
  let raw = null
  try {
    raw = localStorage.getItem(key)
  } catch {
    return
  }
  if (raw === null) return
  const stampedAt = Number(raw)
  if (agentSavedAfter(roadmap.value, items.value, stampedAt)) {
    clearPersistedAgentActive()
    return
  }
  const elapsed = Date.now() - stampedAt
  if (Number.isFinite(stampedAt) && elapsed >= 0 && elapsed < WAITING_TIMEOUT_MS) {
    startWaiting(WAITING_TIMEOUT_MS - elapsed)
  } else {
    clearPersistedAgentActive()
  }
}

function onAgentActive() {
  startWaiting()
  persistAgentActive()
}

const currentPromptText = computed(() =>
  buildRoadmapPrompt(isEmptyRoadmap.value ? 'create' : 'refresh')
)

const REFETCH_UPDATE_TYPES = new Set(['status_changed', 'activated', 'deactivated', 'updated'])

function onProjectUpdated(payload) {
  if (!payload || !REFETCH_UPDATE_TYPES.has(payload.update_type)) return
  onRoadmapUpdated()
}

function onRoadmapUpdated() {
  if (refetchDebounce) clearTimeout(refetchDebounce)
  refetchDebounce = setTimeout(async () => {
    refetchDebounce = null
    if (isPersisting.value) {
      onRoadmapUpdated()
      return
    }
    await fetchRoadmap()
    dismissWaiting()
  }, REFETCH_DEBOUNCE_MS)
}

function buildRoadmapPrompt(mode) {
  const host = typeof window !== 'undefined' ? window.location.host : ''
  return buildRoadmapPromptText(mode, activeProduct.value, host)
}

async function copyToClipboard(text) {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text)
      return true
    }
    throw new Error('insecure-context')
  } catch {
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.focus()
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return ok
    } catch {
      return false
    }
  }
}

async function copyRoadmapPrompt(editedText) {
  const mode = isEmptyRoadmap.value ? 'create' : 'refresh'
  const text = typeof editedText === 'string' ? editedText : buildRoadmapPrompt(mode)
  const ok = await copyToClipboard(text)
  if (ok) {
    showToast({
      message: 'Prompt copied — paste it into the agent connected to THIS account.',
      type: 'success',
    })
  } else {
    showToast({
      message: 'Could not copy automatically. Select and copy the prompt manually.',
      type: 'warning',
    })
  }
}

async function fetchRoadmap({ notify = false } = {}) {
  loading.value = true
  try {
    const { data } = await api.roadmap.get(viewedProductId.value)
    noActiveProduct.value = false
    roadmap.value = data.roadmap || null
    items.value = Array.isArray(data.items) ? [...data.items] : []
  } catch (error) {
    if (error.response?.status === 404) {
      noActiveProduct.value = true
      roadmap.value = null
      items.value = []
    } else {
      console.error('[ROADMAP] Failed to load roadmap:', error)
      if (notify) {
        showToast({ message: 'Failed to load the roadmap. Please try again.', type: 'error' })
      }
    }
  } finally {
    loading.value = false
  }
}

function rebuildFullOrder(newVisibleOrder) {
  const visibleIds = new Set(displayItems.value.map((i) => i.id))
  let vi = 0
  return items.value.map((it) => (visibleIds.has(it.id) ? newVisibleOrder[vi++] : it))
}

function onListReorder(newVisibleOrder) {
  persistOrder(rebuildFullOrder(newVisibleOrder))
}

async function demote(item) {
  const arr = [...items.value]
  const from = arr.findIndex((i) => i.id === item.id)
  if (from < 0 || from === arr.length - 1) return
  const [moved] = arr.splice(from, 1)
  arr.push(moved)
  await persistOrder(arr)
}

async function persistOrder(orderedArr) {
  const previous = items.value
  items.value = orderedArr
  isPersisting.value = true
  try {
    const payload = orderedArr.map((it, i) => ({ id: it.id, sort_order: i }))
    await api.roadmap.reorder(payload, viewedProductId.value)
  } catch (error) {
    console.error('[ROADMAP] Failed to persist new order:', error)
    items.value = previous
    showToast({ message: 'Could not save the new order. Please try again.', type: 'error' })
    await fetchRoadmap()
  } finally {
    isPersisting.value = false
  }
}

async function removeItem(item) {
  if (!item?.id) return
  const previous = items.value
  items.value = items.value.filter((it) => it.id !== item.id)
  try {
    await api.roadmap.removeItem(item.id, viewedProductId.value)
    showToast({ message: 'Removed from roadmap', type: 'success' })
  } catch (error) {
    console.error('[ROADMAP] Failed to remove item:', error)
    items.value = previous
    showToast({ message: 'Could not remove from the roadmap. Please try again.', type: 'error' })
  }
}

const projectDialogRef = ref(null)
const showProjectDialog = ref(false)
const editingProject = ref(null)
const showClearMissionDialog = ref(false)

async function openItem(item) {
  if (item.item_type === 'project') {
    await openProject(item)
  } else {
    await openTask(item)
  }
}

async function openProject(item) {
  const full = await projectStore.fetchProject(item.project_id)
  if (!full) {
    showToast({ message: 'Could not load project details. Please try again.', type: 'error' })
    return
  }
  editingProject.value = full
  showProjectDialog.value = true
}

async function onProjectSaved() {
  editingProject.value = null
  await fetchRoadmap({ notify: true })
}

function onClearMissionConfirmed() {
  projectDialogRef.value?.clearMissionData()
  showClearMissionDialog.value = false
}

function onTypeCreated(newType) {
  if (newType) projectTypes.value.push(newType)
}

const {
  showTaskDialog,
  editingTask,
  saving,
  currentTask,
  editTask,
  cancelTask,
  saveTask,
} = useTaskCrud()

const taskTypeOptions = computed(() => {
  const opts = projectTypes.value.map((t) => ({ title: t.abbreviation, value: t.abbreviation }))
  opts.unshift({ title: '—', value: null })
  return opts
})

async function openTask(item) {
  try {
    const { data } = await api.tasks.get(item.task_id)
    editTask(data)
  } catch (error) {
    console.error('[ROADMAP] Failed to load task details:', error)
    showToast({ message: 'Could not load task details. Please try again.', type: 'error' })
  }
}

function onCurrentTaskUpdate(updated) {
  currentTask.value = updated
}

async function onTaskSave(formRef) {
  await saveTask(formRef, () => fetchRoadmap({ notify: true }))
}

const showConvertConfirm = ref(false)
const conversionItem = ref(null)

function convertTask(item) {
  if (!productStore.effectiveProductId) {
    showToast({ message: 'Activate a product before converting tasks.', type: 'warning' })
    return
  }
  conversionItem.value = item
  showConvertConfirm.value = true
}

async function confirmConvert() {
  showConvertConfirm.value = false
  const item = conversionItem.value
  conversionItem.value = null
  if (!item?.task_id) return
  try {
    const { data } = await api.tasks.convertToProject(item.task_id)
    showToast({ message: `Converted to project: ${data.name}`, type: 'success' })
    await fetchRoadmap({ notify: true })
  } catch (error) {
    console.error('[ROADMAP] Failed to convert task:', error)
    showToast({ message: parseErrorResponse(error).message || 'Failed to convert task to project.', type: 'error' })
  }
}

watch(viewedProductId, () => {
  roadmap.value = null
  items.value = []
  fetchRoadmap()
})

onMounted(async () => {
  unsubRoadmap = wsStore.on('roadmap:updated', onRoadmapUpdated)
  unsubAgentActive = wsStore.on('roadmap:agent_active', onAgentActive)
  unsubProjectUpdate = wsStore.on('project_update', onProjectUpdated)
  unsubHeadlessLifecycle = ['project:staging_complete', 'project:implementation_launched'].map((t) => wsStore.on(t, onRoadmapUpdated))
  unsubResync = registerReconnectResync(async () => {
    await Promise.allSettled([sequenceRunStore.hydrate(), fetchRoadmap()])
    if (waitIsSuperseded(roadmap.value, items.value, agentActiveStorageKey())) dismissWaiting()
  })
  try {
    await Promise.all([productStore.fetchActiveProduct(), fetchRoadmap(), sequenceRunStore.hydrate()])
    rehydrateWaitingFromStorage()
    try {
      const { data } = await api.taxonomyTypes.list()
      projectTypes.value = data || []
    } catch {
      console.error('[ROADMAP] Failed to load taxonomy types')
    }
  } catch (error) {
    console.error('[ROADMAP] Failed to initialize:', error)
  }
})

onUnmounted(() => {
  if (unsubRoadmap) unsubRoadmap()
  if (unsubAgentActive) unsubAgentActive()
  if (unsubProjectUpdate) unsubProjectUpdate()
  unsubHeadlessLifecycle.forEach((u) => u())
  if (unsubResync) unsubResync()
  if (waitingTimeout) clearTimeout(waitingTimeout)
  if (refetchDebounce) clearTimeout(refetchDebounce)
})

defineExpose({
  items,
  displayItems,
  foldInTasks,
  isEmptyRoadmap,
  onListReorder,
  demote,
  removeItem,
  fetchRoadmap,
  waiting,
  isPersisting,
  copyRoadmapPrompt,
  startWaiting,
  dismissWaiting,
  onAgentActive,
  onRoadmapUpdated,
  onProjectUpdated,
  buildRoadmapPrompt,
  currentPromptText,
})
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;
@use '../styles/design-tokens' as *;
@use '../styles/list-filter-bar' as filterBar;

@include filterBar.list-filter-bar;
@include filterBar.list-filter-bar-responsive;

.filter-spacer {
  flex: 1;
}

.rm-product-label {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 0.92rem;
}

.rm-product-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: $color-accent-success;
}

.rm-product-dot--off {
  background: $color-text-muted;
}

.rm-fold-toggle {
  flex: 0 0 auto;
}

.rm-insight {
  margin-bottom: 20px;
}

/* Brand-yellow lightbulb (the AI-insight icon) — overrides the info-blue the
   v-alert type would otherwise tint its prepend icon. */
.rm-insight :deep(.v-alert__prepend .v-icon) {
  color: $color-brand-yellow;
}

.rm-waiting {
  margin-bottom: 20px;
}

.rm-waiting-row {
  display: flex;
  align-items: center;
  gap: 12px;
}

.rm-waiting-spin {
  flex: 0 0 auto;
}

.rm-loading {
  display: flex;
  justify-content: center;
  padding: 48px 0;
}

/* Card list */
.rm-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.rm-row {
  border-radius: $border-radius-md;
  transition: box-shadow $transition-fast ease;
}

/* vuedraggable drop placeholder (the gap the dragged card will land in) */
.rm-ghost {
  opacity: 0.5;
  box-shadow: inset 0 0 0 2px rgba($color-brand-yellow, 0.5);
}

</style>
