<template>
  <v-container>
    <!-- Header (harmonized with ProjectsView / TasksView) -->
    <v-row class="align-center mb-4 main-window-reveal main-window-reveal--hero main-window-delay-1">
      <v-col>
        <h1 class="text-headline-large">Roadmap</h1>
        <p class="text-body-medium text-muted-a11y mt-1">
          An AI-prioritized execution plan from this product's inactive projects and pending tasks, each scored for risk and complexity by your AI agent. Drag to reorder, or convert a task into a project. Implementation starts elsewhere — on the Projects page, or from your connected agent.
          <v-tooltip location="bottom start" max-width="600">
            <template #activator="{ props }">
              <v-icon v-bind="props" size="16" class="help-icon">mdi-help-circle-outline</v-icon>
            </template>
            <div>
              <div class="font-weight-bold mb-1">Roadmap Reference</div>
              <div class="text-body-small mb-2 text-muted-a11y">One roadmap per product</div>
              <div><span class="font-weight-medium">Rank:</span> drag the dotted grip to reorder; the new order is saved automatically and survives a refresh.</div>
              <div class="mt-1"><span class="font-weight-medium">Convert (tasks):</span> promotes the task to a project using the standard conversion.</div>
              <div class="mt-2 text-body-small">The ranking, plus each item's risk and complexity, is generated by your AI agent via the roadmap MCP tool. This page orders work; it does not launch it.</div>
            </div>
          </v-tooltip>
        </p>
      </v-col>
    </v-row>

    <!-- No Product Open -->
    <v-alert
      v-if="noActiveProduct"
      type="info"
      variant="tonal"
      class="ma-4 main-window-reveal main-window-delay-2"
    >
      No product is open. Add a product to view its roadmap.
    </v-alert>

    <template v-else>
      <!-- Toolbar (filter-bar pattern; NO roadmap selector — one per product) -->
      <div class="filter-bar main-window-reveal main-window-delay-2">
        <span class="rm-product-label">
          <span class="rm-product-dot" :class="{ 'rm-product-dot--off': !activeProduct }"></span>
          {{ activeProduct ? activeProduct.name : 'Active product' }}
        </span>
        <div class="filter-spacer"></div>
        <v-switch
          v-model="foldInTasks"
          label="Fold in tasks"
          color="primary"
          density="compact"
          hide-details
          inset
          class="rm-fold-toggle"
        />
        <!-- Two-state copy-prompt bridge: empty roadmap -> Create, else Refresh.
             Copies a build/re-rank prompt (with the viewed product + host baked
             in) for the user to paste into the agent connected to THIS account;
             the passive MCP server can't start analysis itself. -->
        <v-btn
          color="primary"
          variant="flat"
          :prepend-icon="isEmptyRoadmap ? 'mdi-playlist-plus' : 'mdi-refresh'"
          class="rm-copy-btn"
          :aria-label="isEmptyRoadmap ? 'Copy a prompt to create the roadmap' : 'Copy a prompt to refresh the roadmap'"
          @click="copyRoadmapPrompt"
        >
          {{ isEmptyRoadmap ? 'Create Roadmap' : 'Refresh Roadmap' }}
        </v-btn>
      </div>

      <!-- FE-6240: optional user-authored prompt. The checkbox reveals the
           generated prompt in an editable field; the copy button then copies
           the edited text instead of the canned prompt. -->
      <div class="rm-custom-prompt main-window-reveal main-window-delay-2">
        <v-checkbox
          :model-value="customPromptEnabled"
          label="Add my own instructions"
          color="primary"
          density="compact"
          hide-details
          class="rm-custom-toggle"
          @update:model-value="onCustomPromptToggle"
        />
        <v-textarea
          v-if="customPromptEnabled"
          v-model="customPromptText"
          variant="outlined"
          auto-grow
          rows="6"
          hide-details
          class="rm-custom-textarea"
          aria-label="Editable roadmap prompt"
        />
      </div>

      <!-- "Waiting for your agent…" indicator: UI-SET on the copy click (the
           passive MCP server cannot know analysis started), WS-CLEARED on the
           roadmap:updated event (debounced on the LAST write of a conversational
           multi-write), with a manual dismiss + ~2.5min safety timeout. Never
           "Analyzing" — the agent does the work, not the server. -->
      <v-alert
        v-if="waiting"
        type="info"
        variant="tonal"
        density="compact"
        class="rm-waiting main-window-reveal main-window-delay-2"
        closable
        @click:close="dismissWaiting"
      >
        <div class="rm-waiting-row">
          <v-progress-circular indeterminate size="18" width="2" color="primary" class="rm-waiting-spin" />
          <span>
            Waiting for your agent… paste the copied prompt into the agent connected to this account.
            This clears automatically when your agent saves the roadmap.
          </span>
        </div>
      </v-alert>

      <!-- AI-insight banner (sourced from roadmap.summary) -->
      <v-alert
        v-if="roadmap && roadmap.summary"
        type="info"
        variant="tonal"
        density="compact"
        icon="mdi-lightbulb-on-outline"
        class="rm-insight main-window-reveal main-window-delay-2"
      >
        {{ roadmap.summary }}
      </v-alert>

      <!-- Loading -->
      <div v-if="loading && items.length === 0" class="rm-loading">
        <v-progress-circular indeterminate color="primary" size="32" />
      </div>

      <!-- Empty state (product active, but no roadmap items yet) -->
      <v-alert
        v-else-if="items.length === 0"
        type="info"
        variant="tonal"
        class="main-window-reveal main-window-delay-2"
      >
        No roadmap yet. Ask your AI agent to rank this product's inactive projects and pending tasks
        (it writes the roadmap via the <code>save_roadmap</code> MCP tool), then refresh.
      </v-alert>

      <!-- Card list (vuedraggable; drag scoped to the dotted .rm-grip handle so
           the action buttons stay clickable).
           History + FE-9568 reversal: FE-6131e wrapped this list in
           SequenceLauncher so a link-mode checkbox on every card (FE-6176)
           could feed the shared "select projects -> Run sequential" bulk-bar
           flow (the same SequenceLauncher /projects still uses today).
           FE-6180 made an already-linked card's checkbox grey + click through
           to /projects instead of managing the chain here.
           FE-9568 (2026-09-02, operator ruling) reverses plan+launch: /roadmap
           only orders work now. With the selection checkbox gone, nothing on
           this page can ever populate SequenceLauncher's selection, so its
           bulk-bar could never render here again — the wrapper was removed as
           unreachable. Chain launch is unaffected: the identical
           SequenceLauncher still drives "Run sequential" on /projects. -->
      <draggable
        v-else
        :model-value="displayItems"
        item-key="id"
        handle=".rm-grip"
        tag="div"
        class="rm-list main-window-reveal main-window-delay-2"
        ghost-class="rm-ghost"
        :animation="180"
        @update:model-value="onListReorder"
      >
        <template #item="{ element, index }">
          <div class="rm-row">
            <RoadmapCard
              :item="element"
              :rank="index + 1"
              :in-chain="sequenceRunStore.isProjectInActiveChain(element.project_id)"
              @convert="convertTask"
              @open="openItem"
              @demote="demote"
              @remove="removeItem"
            />
          </div>
        </template>
      </draggable>
    </template>

    <!-- Project open: existing create/edit dialog (reused, not rebuilt) -->
    <ProjectCreateEditDialog
      ref="projectDialogRef"
      v-model="showProjectDialog"
      :editing-project="editingProject"
      :active-product="activeProduct"
      :project-types="projectTypes"
      @saved="onProjectSaved"
      @clear-mission="showClearMissionDialog = true"
      @type-created="onTypeCreated"
    />

    <!-- Clear Mission confirm (mirrors ProjectsView) -->
    <BaseDialog
      v-model="showClearMissionDialog"
      type="warning"
      title="Clear Mission?"
      confirm-label="Clear"
      size="sm"
      @confirm="onClearMissionConfirmed"
      @cancel="showClearMissionDialog = false"
    >
      <p>Clear the mission? It will be regenerated on next staging.</p>
    </BaseDialog>

    <!-- Task open: existing task modal (reused via useTaskCrud) -->
    <TaskEditDialog
      v-model="showTaskDialog"
      :editing-task="editingTask"
      :current-task="currentTask"
      :saving="saving"
      :status-select-options="TASK_STATUS_OPTIONS"
      :task-type-options="taskTypeOptions"
      @cancel="cancelTask"
      @save="onTaskSave"
      @update:current-task="onCurrentTaskUpdate"
    />

    <!-- Convert confirmation (mirrors TasksView) -->
    <BaseDialog
      v-model="showConvertConfirm"
      type="info"
      title="Convert to Project"
      icon="mdi-folder-arrow-up"
      confirm-label="Convert"
      @confirm="confirmConvert"
      @cancel="showConvertConfirm = false"
    >
      <p class="text-body-large mb-2">
        Convert task <strong>"{{ conversionItem?.title }}"</strong> to a project?
      </p>
      <p class="text-body-medium text-muted-a11y">
        This creates a new project in the viewed product from the task's title and description.
      </p>
    </BaseDialog>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useProductStore } from '@/stores/products'
import { buildRoadmapPrompt as buildRoadmapPromptText } from '@/content/roadmap/prompts'
import { useProjectStore } from '@/stores/projects'
import { useWebSocketStore } from '@/stores/websocket'
import { useSequenceRunStore } from '@/stores/sequenceRunStore'
import { registerReconnectResync } from '@/stores/websocketEventRouter'
import api from '@/services/api'
import { agentSavedAfter, waitIsSuperseded } from '@/utils/roadmapWaitReconcile'
import { useToast } from '@/composables/useToast'
import { useTaskCrud } from '@/composables/useTaskCrud'
import draggable from 'vuedraggable'
import RoadmapCard from '@/components/RoadmapCard.vue'
import BaseDialog from '@/components/common/BaseDialog.vue'
import ProjectCreateEditDialog from '@/components/projects/ProjectCreateEditDialog.vue'
import TaskEditDialog from './tasks/TaskEditDialog.vue'

const productStore = useProductStore()
const projectStore = useProjectStore()
const wsStore = useWebSocketStore()
const sequenceRunStore = useSequenceRunStore()
const { showToast } = useToast()

// Canonical task statuses (mirrors TaskStatus enum surfaced in TasksView).
const TASK_STATUS_OPTIONS = ['pending', 'in_progress', 'completed', 'blocked', 'cancelled']

// --- State ---
const loading = ref(false)
const noActiveProduct = ref(false)
const roadmap = ref(null)
const items = ref([]) // full, sort_order-ordered (source of truth for reorder)
const foldInTasks = ref(true)
const projectTypes = ref([])

// FE-9502c: same fix as ProjectsView.vue — follows the viewed tab now, not
// the server's single active product (display-only; fetch already used effectiveProductId).
const activeProduct = computed(() => productStore.currentProduct)
const isEmptyRoadmap = computed(() => items.value.length === 0)

// Fold toggle is a pure view filter; reorder always operates on `items` (by id).
const displayItems = computed(() =>
  foldInTasks.value ? items.value : items.value.filter((it) => it.item_type !== 'task'),
)

// --- "Waiting for your agent…" indicator + WS live refresh (Part 4) ---
const waiting = ref(false)
// True while a reorder PATCH is in flight; guards a WS-driven re-fetch from
// clobbering the optimistic order mid-persist.
const isPersisting = ref(false)
let waitingTimeout = null
let refetchDebounce = null
let unsubRoadmap = null
let unsubAgentActive = null
let unsubProjectUpdate = null
let unsubHeadlessLifecycle = []
let unsubResync = null

const WAITING_TIMEOUT_MS = 150000 // ~2.5 min safety auto-clear
const REFETCH_DEBOUNCE_MS = 600 // collapse a conversational multi-write burst

// TSK-6243: the waiting spinner is view-local + in-memory, so a browser reload
// while an agent is mid-build drops it. Stamp the last roadmap:agent_active time
// per active product in localStorage (migration-free, same idiom as
// useProjectFilters; promote to a user-settings DB field only if cross-device
// continuity is later wanted) and re-raise the spinner on mount when the stamp
// is still inside the WAITING_TIMEOUT_MS window. Reuses the existing WS event —
// no @mcp.tool, no schema change, no new store/service.
const AGENT_ACTIVE_STORAGE_PREFIX = 'giljo.roadmap.agentActiveAt.'

function agentActiveStorageKey() {
  const pid = productStore.effectiveProductId
  return pid ? `${AGENT_ACTIVE_STORAGE_PREFIX}${pid}` : null
}

function persistAgentActive() {
  const key = agentActiveStorageKey()
  if (!key) return
  try {
    localStorage.setItem(key, String(Date.now()))
  } catch {
    /* localStorage unavailable (private mode / quota) — non-fatal */
  }
}

function clearPersistedAgentActive() {
  const key = agentActiveStorageKey()
  if (!key) return
  try {
    localStorage.removeItem(key)
  } catch {
    /* non-fatal */
  }
}

function startWaiting(durationMs = WAITING_TIMEOUT_MS) {
  waiting.value = true
  if (waitingTimeout) clearTimeout(waitingTimeout)
  waitingTimeout = setTimeout(() => {
    waiting.value = false
    waitingTimeout = null
    clearPersistedAgentActive() // window lapsed — drop the persisted stamp
  }, durationMs)
}

function dismissWaiting() {
  waiting.value = false
  if (waitingTimeout) {
    clearTimeout(waitingTimeout)
    waitingTimeout = null
  }
  // Agent saved (roadmap:updated) or user dismissed — the build is over, so the
  // reload-continuity stamp is no longer wanted.
  clearPersistedAgentActive()
}

// TSK-6243: on mount, re-raise the spinner if a roadmap:agent_active landed
// within the safety window before a reload. Re-show for the REMAINING time only
// (never re-arm the full window per reload). Skips if a live event already
// raised it during this mount.
function rehydrateWaitingFromStorage() {
  if (waiting.value) return
  const key = agentActiveStorageKey()
  if (!key) return
  let raw = null
  try {
    raw = localStorage.getItem(key)
  } catch {
    return
  }
  if (raw === null) return
  const stampedAt = Number(raw)
  // FE-9407: the agent already answered this wait while we were away.
  if (agentSavedAfter(roadmap.value, items.value, stampedAt)) {
    clearPersistedAgentActive()
    return
  }
  const elapsed = Date.now() - stampedAt
  if (Number.isFinite(stampedAt) && elapsed >= 0 && elapsed < WAITING_TIMEOUT_MS) {
    startWaiting(WAITING_TIMEOUT_MS - elapsed)
  } else {
    clearPersistedAgentActive() // absent/stale/garbage — drop it
  }
}

// FE-6240: the agent's first touch of the roadmap tool (MCP get_roadmap) emits
// a tenant-scoped roadmap:agent_active WS event — THAT raises the waiting
// spinner now, so the trigger is the real agent connection, not the user's
// copy-prompt click. Cleared as before by roadmap:updated (the agent's save)
// or the safety timeout.
function onAgentActive() {
  startWaiting()
  persistAgentActive() // TSK-6243: survive a reload mid-build
}

// FE-6240: "Add my own instructions" — reveal the generated prompt in an
// editable field; copyRoadmapPrompt then copies the edited text. Repopulated
// from the current mode each time it is enabled so it always starts from the
// canned prompt.
const customPromptEnabled = ref(false)
const customPromptText = ref('')

function onCustomPromptToggle(enabled) {
  customPromptEnabled.value = enabled
  if (enabled) {
    customPromptText.value = buildRoadmapPrompt(isEmptyRoadmap.value ? 'create' : 'refresh')
  }
}

// project_update arrives when a project changes OUTSIDE the roadmap (project
// list or an agent). Two display fields on the card are read LIVE from the
// project on every get_roadmap and go stale in the mounted view unless we
// re-fetch:
//   - status      → 'status_changed' | 'activated' | 'deactivated' (a card left
//                    on its old status stays LOCKED).
//   - title+alias → 'updated' (a rename/series change; the backend already
//                    joins title + taxonomy_alias live, so a re-fetch is all
//                    that is needed — bug-2 / alias 0005). Without 'updated' the
//                    card showed the old name/alias until a manual refresh.
// Reuse the same debounced fetchRoadmap so a burst (agent renames/deactivates
// several projects) collapses into one fetch instead of N. Other update types
// (e.g. description-only edits) still re-fetch under 'updated' — cheap and
// debounced, and the read is the single source of truth.
const REFETCH_UPDATE_TYPES = new Set(['status_changed', 'activated', 'deactivated', 'updated'])

function onProjectUpdated(payload) {
  if (!payload || !REFETCH_UPDATE_TYPES.has(payload.update_type)) return
  onRoadmapUpdated()
}

// roadmap:updated arrives once per agent write; debounce so a multi-write
// conversation re-fetches + clears the indicator on the LAST event only.
function onRoadmapUpdated() {
  if (refetchDebounce) clearTimeout(refetchDebounce)
  refetchDebounce = setTimeout(async () => {
    refetchDebounce = null
    // Don't stomp an in-flight optimistic reorder — re-arm and try again once
    // the PATCH settles.
    if (isPersisting.value) {
      onRoadmapUpdated()
      return
    }
    await fetchRoadmap()
    dismissWaiting()
  }, REFETCH_DEBOUNCE_MS)
}

// --- Copy-prompt bridge (Part 1) ---
// The prompt TEXT lives in content/roadmap/prompts.js; this only supplies the
// product being viewed and the host.
function buildRoadmapPrompt(mode) {
  const host = typeof window !== 'undefined' ? window.location.host : ''
  return buildRoadmapPromptText(mode, activeProduct.value, host)
}

// Clipboard write with a secure-context fallback (LAN HTTP has no
// navigator.clipboard). Always wrapped so a failure never throws into the UI.
async function copyToClipboard(text) {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text)
      return true
    }
    throw new Error('insecure-context')
  } catch {
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.focus()
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return ok
    } catch {
      return false
    }
  }
}

async function copyRoadmapPrompt() {
  const mode = isEmptyRoadmap.value ? 'create' : 'refresh'
  // FE-6240: copy the user's edited prompt when "Add my own instructions" is
  // on, otherwise the generated one. The waiting spinner is NO LONGER raised
  // here — it is raised by the roadmap:agent_active WS signal the moment the
  // agent actually touches the roadmap tool, not on this copy click.
  const text = customPromptEnabled.value ? customPromptText.value : buildRoadmapPrompt(mode)
  const ok = await copyToClipboard(text)
  if (ok) {
    showToast({
      message: 'Prompt copied — paste it into the agent connected to THIS account.',
      type: 'success',
    })
  } else {
    showToast({
      message: 'Could not copy automatically. Select and copy the prompt manually.',
      type: 'warning',
    })
  }
}

// --- Fetch ---
// FE-9553: `notify` defaults to FALSE -- silent by default, so a new call site
// cannot add a spurious toast by omission. Reachable from onMounted, a debounced
// WS refetch, and four user actions; only the last may speak. Reasoning pinned
// in tests/unit/views/RoadmapView.spec.js.
async function fetchRoadmap({ notify = false } = {}) {
  loading.value = true
  try {
    const { data } = await api.roadmap.get()
    noActiveProduct.value = false
    roadmap.value = data.roadmap || null
    items.value = Array.isArray(data.items) ? [...data.items] : []
  } catch (error) {
    if (error.response?.status === 404) {
      noActiveProduct.value = true
      roadmap.value = null
      items.value = []
    } else {
      console.error('[ROADMAP] Failed to load roadmap:', error)
      if (notify) {
        showToast({ message: 'Failed to load the roadmap. Please try again.', type: 'error' })
      }
    }
  } finally {
    loading.value = false
  }
}

// --- vuedraggable reorder (drag scoped to the .rm-grip handle) ---
// vuedraggable hands back the reordered VISIBLE list. Because "Fold in tasks" is
// a view-only filter, rebuild the FULL items order from that visible order —
// folded-out tasks keep their absolute slots — then persist over the whole set.
function rebuildFullOrder(newVisibleOrder) {
  const visibleIds = new Set(displayItems.value.map((i) => i.id))
  let vi = 0
  return items.value.map((it) => (visibleIds.has(it.id) ? newVisibleOrder[vi++] : it))
}

function onListReorder(newVisibleOrder) {
  persistOrder(rebuildFullOrder(newVisibleOrder))
}

async function demote(item) {
  const arr = [...items.value]
  const from = arr.findIndex((i) => i.id === item.id)
  if (from < 0 || from === arr.length - 1) return
  const [moved] = arr.splice(from, 1)
  arr.push(moved)
  await persistOrder(arr)
}

// Recompute sort_order = position, PATCH the whole (small) list. Idempotent.
async function persistOrder(orderedArr) {
  const previous = items.value
  items.value = orderedArr // optimistic
  isPersisting.value = true
  try {
    const payload = orderedArr.map((it, i) => ({ id: it.id, sort_order: i }))
    await api.roadmap.reorder(payload)
  } catch (error) {
    console.error('[ROADMAP] Failed to persist new order:', error)
    items.value = previous // rollback
    showToast({ message: 'Could not save the new order. Please try again.', type: 'error' })
    await fetchRoadmap()
  } finally {
    isPersisting.value = false
  }
}

// FE-6022c: optimistic remove → DELETE roadmap_item; rollback on failure.
async function removeItem(item) {
  if (!item?.id) return
  const previous = items.value
  items.value = items.value.filter((it) => it.id !== item.id)
  try {
    await api.roadmap.removeItem(item.id)
    showToast({ message: 'Removed from roadmap', type: 'success' })
  } catch (error) {
    console.error('[ROADMAP] Failed to remove item:', error)
    items.value = previous // rollback
    showToast({ message: 'Could not remove from the roadmap. Please try again.', type: 'error' })
  }
}

const projectDialogRef = ref(null)
const showProjectDialog = ref(false)
const editingProject = ref(null)
const showClearMissionDialog = ref(false)

async function openItem(item) {
  if (item.item_type === 'project') {
    await openProject(item)
  } else {
    await openTask(item)
  }
}

async function openProject(item) {
  // IMP-1002: GET /roadmap returns trimmed items (no description/mission).
  // Fetch the full project first or saving would wipe the orchestrator mission.
  const full = await projectStore.fetchProject(item.project_id)
  if (!full) {
    showToast({ message: 'Could not load project details. Please try again.', type: 'error' })
    return
  }
  editingProject.value = full
  showProjectDialog.value = true
}

async function onProjectSaved() {
  editingProject.value = null
  await fetchRoadmap({ notify: true })
}

function onClearMissionConfirmed() {
  projectDialogRef.value?.clearMissionData()
  showClearMissionDialog.value = false
}

function onTypeCreated(newType) {
  if (newType) projectTypes.value.push(newType)
}

const {
  showTaskDialog,
  editingTask,
  saving,
  currentTask,
  editTask,
  cancelTask,
  saveTask,
} = useTaskCrud()

const taskTypeOptions = computed(() => {
  const opts = projectTypes.value.map((t) => ({ title: t.abbreviation, value: t.abbreviation }))
  opts.unshift({ title: '—', value: null })
  return opts
})

async function openTask(item) {
  try {
    // Fetch the full task (roadmap rows are trimmed) before seeding the dialog.
    const { data } = await api.tasks.get(item.task_id)
    editTask(data)
  } catch (error) {
    console.error('[ROADMAP] Failed to load task details:', error)
    showToast({ message: 'Could not load task details. Please try again.', type: 'error' })
  }
}

function onCurrentTaskUpdate(updated) {
  currentTask.value = updated
}

async function onTaskSave(formRef) {
  // Wrapped, not bare: saveTask calls this with its own args, which would both
  // lose the opt-in and risk landing in the options object.
  await saveTask(formRef, () => fetchRoadmap({ notify: true }))
}

const showConvertConfirm = ref(false)
const conversionItem = ref(null)

function convertTask(item) {
  if (!productStore.effectiveProductId) {
    showToast({ message: 'Activate a product before converting tasks.', type: 'warning' })
    return
  }
  conversionItem.value = item
  showConvertConfirm.value = true
}

async function confirmConvert() {
  showConvertConfirm.value = false
  const item = conversionItem.value
  conversionItem.value = null
  if (!item?.task_id) return
  try {
    const { data } = await api.tasks.convertToProject(item.task_id)
    showToast({ message: `Converted to project: ${data.name}`, type: 'success' })
    await fetchRoadmap({ notify: true })
  } catch (error) {
    console.error('[ROADMAP] Failed to convert task:', error)
    showToast({
      message: error.response?.data?.detail || 'Failed to convert task to project.',
      type: 'error',
    })
  }
}

onMounted(async () => {
  // Live refresh: the agent's roadmap write broadcasts roadmap:updated; re-fetch
  // and clear the waiting indicator. Direct wsStore subscription (same pattern as
  // ActiveProductDisplay.vue) — RoadmapView owns view-local state, no store.
  unsubRoadmap = wsStore.on('roadmap:updated', onRoadmapUpdated)
  // FE-6240: the agent's first roadmap-tool touch (MCP get_roadmap) broadcasts
  // roadmap:agent_active — raise the waiting spinner on the real agent
  // connection (replaces the old optimistic copy-click trigger).
  unsubAgentActive = wsStore.on('roadmap:agent_active', onAgentActive)
  // Live-sync: a project changed OUTSIDE the roadmap fires project_update
  // (status_changed/activated/deactivated/updated, bug-2); reuses the debounced re-fetch.
  unsubProjectUpdate = wsStore.on('project_update', onProjectUpdated)
  // D3 (Headless S3a): a harness-only stage/launch never fired project_update.
  unsubHeadlessLifecycle = ['project:staging_complete', 'project:implementation_launched'].map((t) => wsStore.on(t, onRoadmapUpdated))
  // FE-6165f: hydrate active-chain state at mount + on WS reconnect (a run that
  // finished while disconnected unlocks immediately). FE-9407: a dropped roadmap:updated never replays.
  unsubResync = registerReconnectResync(async () => {
    await Promise.allSettled([sequenceRunStore.hydrate(), fetchRoadmap()])
    if (waitIsSuperseded(roadmap.value, items.value, agentActiveStorageKey())) dismissWaiting()
  })
  try {
    await Promise.all([productStore.fetchActiveProduct(), fetchRoadmap(), sequenceRunStore.hydrate()])
    // TSK-6243: product id is known now — re-show the spinner if an agent was
    // active within the safety window just before this reload.
    rehydrateWaitingFromStorage()
    try {
      const { data } = await api.taxonomyTypes.list()
      projectTypes.value = data || []
    } catch {
      console.error('[ROADMAP] Failed to load taxonomy types')
    }
  } catch (error) {
    console.error('[ROADMAP] Failed to initialize:', error)
  }
})

onUnmounted(() => {
  if (unsubRoadmap) unsubRoadmap()
  if (unsubAgentActive) unsubAgentActive()
  if (unsubProjectUpdate) unsubProjectUpdate()
  unsubHeadlessLifecycle.forEach((u) => u())
  if (unsubResync) unsubResync()
  if (waitingTimeout) clearTimeout(waitingTimeout)
  if (refetchDebounce) clearTimeout(refetchDebounce)
})

// Exposed for unit tests.
defineExpose({
  items,
  displayItems,
  foldInTasks,
  isEmptyRoadmap,
  onListReorder,
  demote,
  removeItem,
  fetchRoadmap,
  waiting,
  isPersisting,
  copyRoadmapPrompt,
  startWaiting,
  dismissWaiting,
  onAgentActive,
  onRoadmapUpdated,
  onProjectUpdated,
  buildRoadmapPrompt,
  customPromptEnabled,
  customPromptText,
  onCustomPromptToggle,
})
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;
@use '../styles/design-tokens' as *;
@use '../styles/list-filter-bar' as filterBar;

@include filterBar.list-filter-bar;
@include filterBar.list-filter-bar-responsive;

.filter-spacer {
  flex: 1;
}

.rm-product-label {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 0.92rem;
}

.rm-product-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: $color-accent-success;
}

.rm-product-dot--off {
  background: $color-text-muted;
}

.rm-fold-toggle {
  flex: 0 0 auto;
}

.rm-insight {
  margin-bottom: 20px;
}

/* Brand-yellow lightbulb (the AI-insight icon) — overrides the info-blue the
   v-alert type would otherwise tint its prepend icon. */
.rm-insight :deep(.v-alert__prepend .v-icon) {
  color: $color-brand-yellow;
}

.rm-waiting {
  margin-bottom: 20px;
}

/* FE-6240: editable custom-prompt block (checkbox + revealed textarea). */
.rm-custom-prompt {
  margin-bottom: 20px;
}

.rm-custom-textarea {
  margin-top: 8px;
}

.rm-waiting-row {
  display: flex;
  align-items: center;
  gap: 12px;
}

.rm-waiting-spin {
  flex: 0 0 auto;
}

.rm-loading {
  display: flex;
  justify-content: center;
  padding: 48px 0;
}

/* Card list */
.rm-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.rm-row {
  border-radius: $border-radius-md;
  transition: box-shadow $transition-fast ease;
}

/* vuedraggable drop placeholder (the gap the dragged card will land in) */
.rm-ghost {
  opacity: 0.5;
  box-shadow: inset 0 0 0 2px rgba($color-brand-yellow, 0.5);
}

</style>
